// apps/web-svelte/src/lib/pages/dashboard/HabitListSection.svelte
<script lang="ts">
  import { Plus, Calendar, Inbox, Archive } from 'lucide-svelte';
  import HabitRow from './HabitRow.svelte';
  import HabitTile from './HabitTile.svelte';
  import type { Habit } from '$lib/types/habit';
  import type { ViewDensity } from './FilterBar.svelte';
  import type { DashboardFilter } from '$lib/dashboard/dashboardHelpers';

  type DropHintPosition = 'above' | 'below' | null;

  let {
    filteredHabits,
    filter,
    viewDensity,
    sortMode,
    allCheckins,
    draggedHabitId,
    dragOverHabitId,
    dropHintPosition,
    onToggle,
    onDetail,
    onDragStart,
    onDragOver,
    onDrop,
    onDragEnd,
    onTouchStart,
    onNavigateAdd
  }: {
    filteredHabits: Habit[];
    filter: DashboardFilter;
    viewDensity: ViewDensity;
    sortMode: 'custom' | 'smart';
    allCheckins: Record<string, number>;
    draggedHabitId: string | null;
    dragOverHabitId: string | null;
    dropHintPosition: DropHintPosition;
    onToggle: (habit: Habit) => void;
    onDetail: (habit: Habit) => void;
    onDragStart: (habit: Habit, e: DragEvent) => void;
    onDragOver: (habit: Habit, e: DragEvent) => void;
    onDrop: (habit: Habit, e: DragEvent) => void;
    onDragEnd: () => void;
    onTouchStart: (habit: Habit, e: TouchEvent) => void;
    onNavigateAdd: () => void;
  } = $props();

  const FILTER_EMPTY: Record<DashboardFilter, { icon: typeof Inbox; title: string; subtitle: string }> = {
    pending: { icon: Calendar, title: 'All done for now', subtitle: 'Nothing left pending today' },
    all: { icon: Inbox, title: 'No habits yet', subtitle: 'Create your first habit to get started' },
    done: { icon: Calendar, title: 'Nothing completed today', subtitle: 'Complete a habit and it will appear here' },
    archived: { icon: Archive, title: 'No archived habits', subtitle: 'Archived habits will appear here' }
  };

  const emptyInfo = $derived(FILTER_EMPTY[filter]);

  // Group by tag when filter is 'all' and sort is 'custom'
  const groupByTag = $derived(filter === 'all' && sortMode === 'custom');

  type GroupedHabits = Array<{ tag: string | null; habits: Habit[] }>;

  const groups: GroupedHabits = $derived.by(() => {
    if (!groupByTag || filteredHabits.length === 0) return [{ tag: null, habits: filteredHabits }];
    const tagMap = new Map<string, Habit[]>();
    const untagged: Habit[] = [];
    for (const h of filteredHabits) {
      if (h.tags.length === 0) { untagged.push(h); continue; }
      // Put in first tag group
      const first = h.tags[0];
      if (!tagMap.has(first)) tagMap.set(first, []);
      tagMap.get(first)!.push(h);
    }
    const result: GroupedHabits = [];
    for (const [tag, habits] of tagMap) result.push({ tag, habits });
    if (untagged.length > 0) result.push({ tag: null, habits: untagged });
    return result;
  });
</script>

<div class="max-w-2xl mx-auto px-4 pt-4 pb-32">
  {#if filteredHabits.length === 0}
    <div class="flex flex-col items-center justify-center py-16 text-center animate-fade-slide-up">
      <div class="w-14 h-14 rounded-2xl border border-border bg-bg-secondary flex items-center justify-center mb-3">
        <svelte:component this={emptyInfo.icon} size={24} class="text-muted" />
      </div>
      <p class="text-sm font-semibold text-foreground mb-1">{emptyInfo.title}</p>
      <p class="text-xs font-mono text-muted mb-4">{emptyInfo.subtitle}</p>
      {#if filter === 'all'}
        <button
          type="button"
          onclick={onNavigateAdd}
          class="px-4 py-2 rounded-xl border border-accent bg-accent/10 text-accent text-xs font-mono uppercase tracking-wider hover:bg-accent/20 transition-colors flex items-center gap-1.5"
        >
          <Plus size={14} /> Add first habit
        </button>
      {/if}
    </div>
  {:else}
    {#each groups as group}
      {#if groupByTag && group.tag}
        <div class="mb-2 mt-4 first:mt-0">
          <h3 class="text-[10px] font-mono text-muted uppercase tracking-widest px-2">#{group.tag}</h3>
        </div>
      {/if}
      {#if viewDensity === 'comfortable'}
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {#each group.habits as habit, index (habit.id)}
            <HabitTile
              {habit}
              onToggle={() => onToggle(habit)}
              onDetail={() => onDetail(habit)}
              {allCheckins}
              appearanceIndex={index}
            />
          {/each}
        </div>
      {:else}
        <div role="list" class="space-y-0.5">
          {#each group.habits as habit, index (habit.id)}
            <HabitRow
              {habit}
              onToggle={() => onToggle(habit)}
              onDetail={() => onDetail(habit)}
              onDragStart={(e) => onDragStart(habit, e)}
              onDragOver={(e) => onDragOver(habit, e)}
              onDrop={(e) => onDrop(habit, e)}
              onDragEnd={onDragEnd}
              onTouchStart={(e) => onTouchStart(habit, e)}
              isDragging={draggedHabitId === habit.id}
              isDropTarget={dragOverHabitId === habit.id}
              dropHintPosition={dragOverHabitId === habit.id ? dropHintPosition : null}
              appearanceIndex={index}
            />
          {/each}
        </div>
      {/if}
    {/each}
  {/if}
</div>

// packages/web/src/pages/components/HabitListSection.tsx
import React from 'react';
import { HabitRow, HabitTile, DropIndicator } from './DashboardView.helpers';
import type { Habit } from '@/types/habit';
import type { DashboardViewProps, ViewDensity } from './DashboardHero';

const FILTER_EMPTY_STATES: Record<
  DashboardViewProps['filter'],
  { title: string; subtitle: string; emoji: string }
> = {
  pending: {
    title: 'All done for today!',
    subtitle: 'Enjoy the break or set up a new habit when you’re ready.',
    emoji: '🎉'
  },
  done: {
    title: 'No completed habits yet',
    subtitle: 'Complete a habit to track streaks and stats.',
    emoji: '✨'
  },
  all: {
    title: 'No habits yet',
    subtitle: 'Add your first habit to start building momentum.',
    emoji: '👋'
  },
  archived: {
    title: 'No archived habits',
    subtitle: 'Archive habits here once you want to pause them.',
    emoji: '🗂️'
  }
};

export function HabitListSection({
  filtered,
  dropHint,
  dragOverHabitId,
  draggedHabitId,
  handleToggle,
  handleDrop,
  handleDragStart,
  handleDragOver,
  handleDragEnd,
  handleTouchStart,
  navigate,
  selectedTags,
  viewDensity,
  filter
}: Pick<
  DashboardViewProps,
  | 'filtered'
  | 'dropHint'
  | 'dragOverHabitId'
  | 'draggedHabitId'
  | 'handleToggle'
  | 'handleDrop'
  | 'handleDragStart'
  | 'handleDragOver'
  | 'handleDragEnd'
  | 'handleTouchStart'
  | 'navigate'
  | 'selectedTags'
  | 'viewDensity'
  | 'filter'
>) {
  if (filtered.length === 0) {
    const emptyState = FILTER_EMPTY_STATES[filter];
    const message = selectedTags.length > 0
      ? `No habits match ${selectedTags.join(', ')} under this filter.`
      : emptyState.subtitle;
    return (
      <div className="max-w-2xl mx-auto py-16 flex flex-col items-center justify-center gap-3 text-center text-muted">
        <div className="text-4xl">{emptyState.emoji}</div>
        <h2 className="text-2xl font-semibold text-foreground">{emptyState.title}</h2>
        <p className="text-sm text-muted max-w-md">{message}</p>
        <button
          type="button"
          onClick={() => navigate('/habit/new')}
          className="px-5 py-2 rounded-2xl bg-accent text-white text-sm font-semibold uppercase tracking-widest transition hover:opacity-90"
        >
          Add a habit
        </button>
      </div>
    );
  }
  const isGrid = viewDensity === 'comfortable';
  let animationIndex = 0;

  const renderHabitItem = (habit: Habit, key: string) => {
    const index = animationIndex++;
    if (isGrid) {
      return (
        <HabitTile
          key={key}
          habit={habit}
          onToggle={() => { void handleToggle(habit); }}
          onDetail={() => navigate(`/habit/${habit.id}`)}
          appearanceIndex={index}
        />
      );
    }
    return (
      <HabitRowEntry
        key={key}
        habit={habit}
        dropHint={dropHint}
        dragOverHabitId={dragOverHabitId}
        draggedHabitId={draggedHabitId}
        handleToggle={handleToggle}
        handleDrop={handleDrop}
        handleDragStart={handleDragStart}
        handleDragOver={handleDragOver}
        handleDragEnd={handleDragEnd}
        handleTouchStart={handleTouchStart}
        navigate={navigate}
        viewDensity={viewDensity}
        appearanceIndex={index}
      />
    );
  };

  if (isGrid) {
    return (
      <div
        className="w-full max-w-6xl mx-auto py-3 px-4 sm:px-6 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3"
        role="list"
        aria-label="Habit list"
      >
        {selectedTags.length > 0 ? (
          selectedTags.map((tag) => {
            const habitsInTag = filtered.filter((h) => h.tags.includes(tag));
            if (habitsInTag.length === 0) return null;
            return (
              <React.Fragment key={tag}>
                <div className="col-span-full flex items-center gap-2 px-1 mt-2 first:mt-0">
                  <span className="w-1.5 h-1.5 rounded-full bg-accent" />
                  <h3 className="text-[10px] font-mono font-bold uppercase tracking-widest text-muted">{tag}</h3>
                </div>
                {habitsInTag.map((habit) => renderHabitItem(habit, `${tag}-${habit.id}`))}
              </React.Fragment>
            );
          })
        ) : (
          filtered.map((habit) => renderHabitItem(habit, habit.id))
        )}
      </div>
    );
  }

  return (
    <div
      className="w-full max-w-2xl mx-auto py-3 flex flex-col px-4 sm:px-6"
      style={{ gap: '0.25rem' }}
      role="list"
      aria-label="Habit list"
    >
      {selectedTags.length > 0 ? (
        selectedTags.map((tag) => {
          const habitsInTag = filtered.filter((h) => h.tags.includes(tag));
          if (habitsInTag.length === 0) {
            return null;
          }
          return (
            <div key={tag} className="space-y-1 mb-3">
              <div className="flex items-center gap-2 px-1">
                <span className="w-1.5 h-1.5 rounded-full bg-accent" />
                <h3 className="text-[10px] font-mono font-bold uppercase tracking-widest text-muted">{tag}</h3>
              </div>
              {habitsInTag.map((habit) => renderHabitItem(habit, `${tag}-${habit.id}`))}
            </div>
          );
        })
      ) : (
        filtered.map((habit) => renderHabitItem(habit, habit.id))
      )}
    </div>
  );
}

type HabitRowEntryProps = {
  habit: Habit;
  dropHint: { habitId: string; position: 'above' | 'below' } | null;
  dragOverHabitId: string | null;
  draggedHabitId: string | null;
  handleToggle: (habit: Habit) => Promise<void>;
  handleDrop: (event: React.DragEvent<HTMLDivElement>, habitId: string) => Promise<void>;
  handleDragStart: (event: React.DragEvent<HTMLDivElement>, habitId: string) => void;
  handleDragOver: (event: React.DragEvent<HTMLDivElement>, habitId: string) => void;
  handleDragEnd: () => void;
  handleTouchStart: (event: React.TouchEvent, habitId: string) => void;
  navigate: (to: string) => void;
  viewDensity: ViewDensity;
  appearanceIndex: number;
};

function HabitRowEntry({
  habit,
  dropHint,
  dragOverHabitId,
  draggedHabitId,
  handleToggle,
  handleDrop,
  handleDragStart,
  handleDragOver,
  handleDragEnd,
  handleTouchStart,
  navigate,
  viewDensity,
  appearanceIndex
}: HabitRowEntryProps) {
  const dropHintPosition = dropHint?.habitId === habit.id ? dropHint.position : null;
  const isDragging = draggedHabitId === habit.id;
  const showDropAbove = dropHintPosition === 'above';
  const showDropBelow = dropHintPosition === 'below';

  return (
    <React.Fragment>
      {showDropAbove && <DropIndicator />}
      <HabitRow
        habit={habit}
        onToggle={() => {
          void handleToggle(habit);
        }}
        onDetail={() => navigate(`/habit/${habit.id}`)}
        onDragStart={(event) => handleDragStart(event, habit.id)}
        onDragOver={(event) => handleDragOver(event, habit.id)}
        onDrop={(event) => {
          void handleDrop(event, habit.id);
        }}
        onDragEnd={handleDragEnd}
        onTouchStart={(event) => handleTouchStart(event, habit.id)}
        isDropTarget={dragOverHabitId === habit.id}
        isDragging={isDragging}
        dropHintPosition={dropHintPosition}
        viewDensity={viewDensity}
        appearanceIndex={appearanceIndex}
      />
      {showDropBelow && <DropIndicator />}
    </React.Fragment>
  );
}
