// packages/web/src/components/UndoToast.tsx
import React from 'react';

interface Props {
  message: string;
  actionLabel?: string;
  onAction?: () => void;
  onClose: () => void;
}

export function UndoToast({ message, actionLabel, onAction, onClose }: Props) {
  const hasAction = Boolean(actionLabel && onAction);
  return (
    <div className="fixed left-1/2 bottom-6 z-50 w-full max-w-lg -translate-x-1/2 bg-bg-secondary/90 backdrop-blur-xl border border-border rounded-2xl px-4 py-3 shadow-xl flex items-center justify-between gap-4 text-sm text-foreground">
      <div>
        <p className="text-[11px] font-mono uppercase tracking-[0.3em] text-muted">{hasAction ? 'undo' : 'notice'}</p>
        <p className="mt-1 text-base font-semibold">{message}</p>
      </div>
      <div className="flex items-center gap-2">
        {hasAction && (
          <button
            type="button"
            className="rounded-full border border-accent px-3 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-accent transition hover:border-accent-secondary/60"
            onClick={onAction}
          >
            {actionLabel}
          </button>
        )}
        <button
          type="button"
          className="text-xs font-mono uppercase tracking-[0.3em] text-muted"
          onClick={onClose}
        >
          ×
        </button>
      </div>
    </div>
  );
}

// apps/web/src/lib/components/UndoToast.svelte
<script lang="ts">
  type Props = {
    message: string;
    actionLabel?: string;
    onAction?: () => void | Promise<void>;
    onClose: () => void;
  };

  let { message, actionLabel, onAction, onClose }: Props = $props();

  const hasAction = $derived(Boolean(actionLabel && onAction));
</script>

<div class="fixed bottom-6 left-1/2 z-50 flex w-full max-w-lg -translate-x-1/2 items-center justify-between gap-4 rounded-2xl border border-border bg-bg-secondary/90 px-4 py-3 text-sm text-foreground shadow-xl backdrop-blur-xl">
  <div>
    <p class="text-[11px] font-mono uppercase tracking-[0.3em] text-muted">{hasAction ? 'undo' : 'notice'}</p>
    <p class="mt-1 text-base font-semibold">{message}</p>
  </div>

  <div class="flex items-center gap-2">
    {#if hasAction}
      <button
        type="button"
        class="rounded-full border border-accent px-3 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-accent transition hover:border-accent-secondary/60"
        onclick={onAction}
      >
        {actionLabel}
      </button>
    {/if}

    <button
      type="button"
      class="text-xs font-mono uppercase tracking-[0.3em] text-muted"
      onclick={onClose}
    >
      x
    </button>
  </div>
</div>
