// design-v2/src/pages/Dashboard.tsx
import React, { useState } from 'react';
import {
  CheckIcon,
  ChevronRightIcon,
  FlameIcon,
  TrendingUpIcon,
  ZapIcon } from
'lucide-react';
import { CompletionRing } from '../components/CompletionRing';
import { MiniHeatmap } from '../components/MiniHeatmap';
import { Habit } from '../types/habit';
import { useHabits } from '../hooks/useHabits';
interface DashboardProps {
  onNavigate: (view: string, habitId?: string) => void;
}
const colorAccent: Record<
  string,
  {
    text: string;
    bg: string;
    border: string;
    glow: string;
  }> =
{
  blue: {
    text: 'text-[#00d4ff]',
    bg: 'bg-[#00d4ff]/10',
    border: 'border-[#00d4ff]/30',
    glow: 'shadow-[0_0_12px_rgba(0,212,255,0.2)]'
  },
  green: {
    text: 'text-[#00ff88]',
    bg: 'bg-[#00ff88]/10',
    border: 'border-[#00ff88]/30',
    glow: 'shadow-[0_0_12px_rgba(0,255,136,0.2)]'
  },
  purple: {
    text: 'text-purple-400',
    bg: 'bg-purple-400/10',
    border: 'border-purple-400/30',
    glow: 'shadow-[0_0_12px_rgba(168,85,247,0.2)]'
  },
  orange: {
    text: 'text-orange-400',
    bg: 'bg-orange-400/10',
    border: 'border-orange-400/30',
    glow: 'shadow-[0_0_12px_rgba(249,115,22,0.2)]'
  },
  red: {
    text: 'text-red-400',
    bg: 'bg-red-400/10',
    border: 'border-red-400/30',
    glow: 'shadow-[0_0_12px_rgba(239,68,68,0.2)]'
  },
  cyan: {
    text: 'text-cyan-400',
    bg: 'bg-cyan-400/10',
    border: 'border-cyan-400/30',
    glow: 'shadow-[0_0_12px_rgba(34,211,238,0.2)]'
  }
};
function HabitRow({
  habit,
  onToggle,
  onDetail




}: {habit: Habit;onToggle: () => void;onDetail: () => void;}) {
  const today = new Date().toISOString().split('T')[0];
  const completed = !!habit.completions[today];
  const accent = colorAccent[habit.color];
  // Calculate current streak
  let streak = 0;
  const d = new Date();
  while (true) {
    const key = d.toISOString().split('T')[0];
    if (habit.completions[key]) {
      streak++;
      d.setDate(d.getDate() - 1);
    } else {
      break;
    }
  }
  // Last 7 days mini bars
  const last7 = Array.from(
    {
      length: 7
    },
    (_, i) => {
      const date = new Date();
      date.setDate(date.getDate() - (6 - i));
      return !!habit.completions[date.toISOString().split('T')[0]];
    }
  );
  // Completion rate last 30 days
  let rate30 = 0;
  for (let i = 0; i < 30; i++) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    if (habit.completions[date.toISOString().split('T')[0]]) rate30++;
  }
  const completionRate = Math.round(rate30 / 30 * 100);
  return (
    <div
      className={`group flex items-center gap-3 px-4 py-3 border-b border-[#1e1e2e] hover:bg-[#0f0f1a] transition-colors cursor-pointer ${completed ? 'opacity-100' : 'opacity-90'}`}>

      {/* Checkbox */}
      <button
        onClick={(e) => {
          e.stopPropagation();
          onToggle();
        }}
        className={`flex-shrink-0 w-5 h-5 rounded border-2 flex items-center justify-center transition-all duration-200 ${completed ? `${accent.bg} ${accent.border} ${accent.glow}` : 'border-[#2e2e3e] hover:border-[#3e3e4e]'}`}
        aria-label={`Mark ${habit.name} as ${completed ? 'incomplete' : 'complete'}`}>

        {completed &&
        <CheckIcon size={11} className={accent.text} strokeWidth={3} />
        }
      </button>

      {/* Icon + Name */}
      <button
        onClick={onDetail}
        className="flex items-center gap-2.5 flex-1 min-w-0 text-left">

        <span className="text-base leading-none">{habit.icon}</span>
        <div className="min-w-0">
          <div
            className={`text-sm font-medium ${completed ? 'text-[#64748b] line-through' : 'text-white'} truncate`}>

            {habit.name}
          </div>
          <div className="flex items-center gap-2 mt-0.5">
            {habit.tags.slice(0, 2).map((tag) =>
            <span
              key={tag}
              className={`text-[10px] font-mono ${accent.text} opacity-70`}>

                #{tag}
              </span>
            )}
          </div>
        </div>
      </button>

      {/* 30-day Mini Heatmap */}
      <div className="hidden sm:flex items-center justify-end mr-2">
        <MiniHeatmap completions={habit.completions} color={habit.color} />
      </div>

      {/* Last 7 days mini bars */}
      <div className="hidden sm:flex items-end gap-[2px] h-5">
        {last7.map((done, i) =>
        <div
          key={i}
          className="w-[4px] rounded-sm transition-all"
          style={{
            height: done ? '100%' : '30%',
            backgroundColor: done ?
            habit.color === 'green' ?
            '#00ff88' :
            '#00d4ff' :
            '#1e1e2e',
            opacity: i === 6 ? 1 : 0.5 + i * 0.07
          }} />

        )}
      </div>

      {/* Streak */}
      <div className="hidden md:flex items-center gap-1 w-16 justify-end">
        {streak > 0 &&
        <>
            <FlameIcon size={11} className="text-orange-400" />
            <span className="text-[11px] font-mono text-orange-400">
              {streak}
            </span>
          </>
        }
      </div>

      {/* Completion ring */}
      <CompletionRing
        percentage={completionRate}
        size={32}
        strokeWidth={2.5}
        color={habit.color}
        showText={false} />


      {/* Chevron */}
      <button
        onClick={onDetail}
        className="text-[#2e2e3e] group-hover:text-[#64748b] transition-colors">

        <ChevronRightIcon size={14} />
      </button>
    </div>);

}
export function Dashboard({ onNavigate }: DashboardProps) {
  const { habits, toggleCompletion, getTodayCompletionRate } = useHabits();
  const [filter, setFilter] = useState<'all' | 'pending' | 'done'>('all');
  const today = new Date().toISOString().split('T')[0];
  const todayRate = getTodayCompletionRate();
  const completedToday = habits.filter((h) => h.completions[today]).length;
  const totalActive = habits.length;
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'short',
    day: 'numeric'
  });
  const filtered = habits.filter((h) => {
    if (filter === 'pending') return !h.completions[today];
    if (filter === 'done') return !!h.completions[today];
    return true;
  });
  // Overall streak (days where all habits completed)
  let overallStreak = 0;
  const d = new Date();
  d.setDate(d.getDate() - 1);
  for (let i = 0; i < 30; i++) {
    const key = d.toISOString().split('T')[0];
    const allDone = habits.every((h) => h.completions[key]);
    if (allDone) {
      overallStreak++;
      d.setDate(d.getDate() - 1);
    } else break;
  }
  return (
    <div className="min-h-screen bg-[#080810] pt-14">
      {/* Header */}
      <div className="border-b border-[#1e1e2e] bg-[#080810] px-4 py-4">
        <div className="max-w-2xl mx-auto">
          <div className="flex items-start justify-between mb-4">
            <div>
              <p className="text-[11px] font-mono text-[#64748b] uppercase tracking-widest mb-1">
                {dateStr}
              </p>
              <h1 className="text-xl font-semibold text-white">Today</h1>
            </div>
            <div className="text-right">
              <div
                className="text-3xl font-mono font-bold text-[#00d4ff]"
                style={{
                  textShadow: '0 0 20px rgba(0,212,255,0.5)'
                }}>

                {todayRate}%
              </div>
              <div className="text-[10px] font-mono text-[#64748b]">
                {completedToday}/{totalActive} done
              </div>
            </div>
          </div>

          {/* Progress bar */}
          <div className="h-1 bg-[#1e1e2e] rounded-full overflow-hidden mb-4">
            <div
              className="h-full rounded-full transition-all duration-700"
              style={{
                width: `${todayRate}%`,
                background: 'linear-gradient(90deg, #00d4ff, #00ff88)',
                boxShadow: '0 0 8px rgba(0,212,255,0.6)'
              }} />

          </div>

          {/* Stats row */}
          <div className="grid grid-cols-3 gap-2">
            <div className="bg-[#0f0f1a] border border-[#1e1e2e] rounded-lg px-3 py-2">
              <div className="flex items-center gap-1.5 mb-1">
                <ZapIcon size={10} className="text-[#00d4ff]" />
                <span className="text-[10px] font-mono text-[#64748b] uppercase tracking-wider">
                  Active
                </span>
              </div>
              <span className="text-lg font-mono font-bold text-white">
                {totalActive}
              </span>
            </div>
            <div className="bg-[#0f0f1a] border border-[#1e1e2e] rounded-lg px-3 py-2">
              <div className="flex items-center gap-1.5 mb-1">
                <FlameIcon size={10} className="text-orange-400" />
                <span className="text-[10px] font-mono text-[#64748b] uppercase tracking-wider">
                  Streak
                </span>
              </div>
              <span className="text-lg font-mono font-bold text-orange-400">
                {overallStreak}d
              </span>
            </div>
            <div className="bg-[#0f0f1a] border border-[#1e1e2e] rounded-lg px-3 py-2">
              <div className="flex items-center gap-1.5 mb-1">
                <TrendingUpIcon size={10} className="text-[#00ff88]" />
                <span className="text-[10px] font-mono text-[#64748b] uppercase tracking-wider">
                  Done
                </span>
              </div>
              <span className="text-lg font-mono font-bold text-[#00ff88]">
                {completedToday}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Filter tabs */}
      <div className="border-b border-[#1e1e2e] px-4">
        <div className="max-w-2xl mx-auto flex gap-0">
          {(['all', 'pending', 'done'] as const).map((f) =>
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-2.5 text-xs font-mono uppercase tracking-wider border-b-2 transition-colors ${filter === f ? 'border-[#00d4ff] text-[#00d4ff]' : 'border-transparent text-[#64748b] hover:text-white'}`}>

              {f}
              {f === 'pending' &&
            <span className="ml-1.5 text-[9px] bg-[#1e1e2e] px-1 py-0.5 rounded font-mono">
                  {habits.filter((h) => !h.completions[today]).length}
                </span>
            }
            </button>
          )}
        </div>
      </div>

      {/* Habit list */}
      <div className="max-w-2xl mx-auto">
        {filtered.length === 0 ?
        <div className="flex flex-col items-center justify-center py-16 text-[#64748b]">
            <div className="text-4xl mb-3">✓</div>
            <p className="font-mono text-sm">All habits completed!</p>
          </div> :

        filtered.map((habit) =>
        <HabitRow
          key={habit.id}
          habit={habit}
          onToggle={() => toggleCompletion(habit.id)}
          onDetail={() => onNavigate('detail', habit.id)} />

        )
        }
      </div>
    </div>);

}

// apps/web/src/routes/(protected)/dashboard/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { resolve } from '$app/paths';
  import { Flame, Plus, Search, Zap, TrendingUp, GripVertical } from 'lucide-svelte';
  import CompletionRing from '$lib/components/CompletionRing.svelte';
  import MiniHeatmap from '$lib/components/MiniHeatmap.svelte';
  import Onboarding from '$lib/components/Onboarding.svelte';
  import RemindersPanel from '$lib/components/RemindersPanel.svelte';
  import type { OnboardingTemplate } from '$lib/components/onboarding';
  import { formatAppDate } from '@/lib/i18n';
  import { calculateScheduledCompletionRate, calculateScheduledStreak, getScheduleStatusForDate } from '$lib/habits/schedule';
  import { formatDate } from '$lib/habits/habitStats';
  import { habitsStore } from '$lib/stores/habits';
  import { HABIT_COLOR_THEMES } from '$lib/theme/habit-colors';
  import type { Habit } from '@/types/habit';

  type DashboardFilter = 'all' | 'pending' | 'done' | 'archived';

  let addingTemplate = $state<string | null>(null);
  let filter = $state<DashboardFilter>('all');
  let searchQuery = $state('');

  const todayDate = $derived.by(() => { const n = new Date(); return new Date(n.getFullYear(), n.getMonth(), n.getDate()); });
  const todayKey = $derived(formatDate(todayDate));
  const dateStr = $derived(formatAppDate(todayDate, { weekday: 'long', month: 'short', day: 'numeric' }));

  const activeHabits = $derived($habitsStore.habits);

  const scheduledToday = $derived(
    activeHabits.filter((h) => getScheduleStatusForDate(h, todayDate) === 'scheduled')
  );

  const completedTodayCount = $derived(
    scheduledToday.filter((h) => {
      const target = Math.max(1, h.dailyTarget ?? 1);
      return (h.completions[todayKey] ?? 0) >= target;
    }).length
  );

  const todayRate = $derived(
    scheduledToday.length > 0 ? Math.round((completedTodayCount / scheduledToday.length) * 100) : 0
  );

  const overallStreak = $derived.by(() => {
    if (activeHabits.length === 0) { return 0; }
    return Math.max(...activeHabits.map((h) => calculateScheduledStreak(h, h.completions).current));
  });

  const filteredHabits = $derived.by(() => {
    let list: Habit[];
    switch (filter) {
      case 'pending':
        list = activeHabits.filter((h) => {
          const target = Math.max(1, h.dailyTarget ?? 1);
          return (h.completions[todayKey] ?? 0) < target;
        });
        break;
      case 'done':
        list = activeHabits.filter((h) => {
          const target = Math.max(1, h.dailyTarget ?? 1);
          return (h.completions[todayKey] ?? 0) >= target;
        });
        break;
      case 'archived':
        list = $habitsStore.allHabits.filter((h) => h.archived);
        break;
      default:
        list = activeHabits;
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      list = list.filter(
        (h) =>
          h.name.toLowerCase().includes(q) ||
          h.tags.some((t) => t.toLowerCase().includes(q))
      );
    }
    return list;
  });

  function buildLast7(habit: Habit, todayStart: Date) {
    return Array.from({ length: 7 }, (_, i) => {
      const key = formatDate(new Date(todayStart.getTime() + (i - 6) * 86_400_000));
      const target = Math.max(1, habit.dailyTarget ?? 1);
      return (habit.completions[key] ?? 0) >= target;
    });
  }

  async function toggleHabit(habit: Habit) {
    await habitsStore.advanceCompletionCount(habit.id, todayKey);
  }

  function navigateToDetail(habitId: string) {
    void goto(resolve('/(protected)/habit/[id]', { id: habitId }));
  }

  function navigateToNewHabit() {
    void goto(resolve<'/(protected)/habit/new'>('/(protected)/habit/new', {}));
  }

  // Drag-and-drop reorder (only in 'all' view with no search)
  let dragId = $state<string | null>(null);
  let dragOverId = $state<string | null>(null);

  function isDragActive() {
    return filter === 'all' && !searchQuery.trim();
  }

  function onDragStart(e: DragEvent, habitId: string) {
    dragId = habitId;
    e.dataTransfer!.effectAllowed = 'move';
    e.dataTransfer!.setData('text/plain', habitId);
  }

  function onDragOver(e: DragEvent, habitId: string) {
    e.preventDefault();
    e.dataTransfer!.dropEffect = 'move';
    if (habitId !== dragId) dragOverId = habitId;
  }

  function onDragLeave() {
    dragOverId = null;
  }

  async function onDrop(e: DragEvent, targetId: string) {
    e.preventDefault();
    dragOverId = null;
    if (!dragId || dragId === targetId) { dragId = null; return; }
    const items = [...filteredHabits];
    const fromIdx = items.findIndex((h) => h.id === dragId);
    const toIdx = items.findIndex((h) => h.id === targetId);
    if (fromIdx < 0 || toIdx < 0) { dragId = null; return; }
    items.splice(toIdx, 0, items.splice(fromIdx, 1)[0]);
    const step = 1_000;
    const base = Date.now();
    for (let i = 0; i < items.length; i++) {
      const newOrder = base + i * step;
      if (items[i].sortOrder !== newOrder) {
        void habitsStore.updateHabit(items[i].id, { sortOrder: newOrder });
      }
    }
    dragId = null;
  }

  function onDragEnd() {
    dragId = null;
    dragOverId = null;
  }

  async function handleTemplateSelect(template: OnboardingTemplate) {
    addingTemplate = template.name;
    try {
      const allHabits = $habitsStore.allHabits;
      const sortOrder =
        allHabits.length > 0
          ? Math.max(...allHabits.map((h) => h.sortOrder ?? 0)) + 1
          : 0;
      const habitId = await habitsStore.addHabit({
        name: template.name,
        description: template.description,
        icon: template.icon,
        color: template.color,
        tags: template.tags,
        frequency: template.frequency,
        customDays: template.customDays,
        targetStreak: template.targetStreak,
        dailyTarget: 1,
        type: 'positive',
        freezeDays: [],
        archived: false,
        sortOrder
      });
      await goto(resolve('/(protected)/habit/[id]', { id: habitId }));
    } finally {
      addingTemplate = null;
    }
  }
</script>

<svelte:head>
  <title>Dashboard - Habbit Runner</title>
</svelte:head>

{#if $habitsStore.habits.length === 0}
  <Onboarding onCreateCustom={navigateToNewHabit} onTemplateSelect={handleTemplateSelect} activeTemplate={addingTemplate} />
{:else}
  <div class="min-h-screen bg-bg-primary">
    <!-- Hero -->
    <div class="border-b border-border bg-bg-secondary/50 px-4 py-4 backdrop-blur-sm">
      <div class="mx-auto max-w-2xl">
        <p class="text-[11px] font-mono uppercase tracking-widest text-muted">{dateStr}</p>
        <div class="mt-3 flex items-center gap-4">
          <CompletionRing percentage={todayRate} size={52} strokeWidth={4} showText={true} />
          <div class="grid flex-1 grid-cols-3 gap-2">
            <div class="rounded-xl border border-border bg-bg-card px-3 py-2">
              <div class="mb-1 flex items-center gap-1">
                <Zap size={10} class="text-accent" />
                <span class="text-[10px] font-mono uppercase tracking-wider text-muted">Active</span>
              </div>
              <span class="text-base font-mono font-bold text-foreground">{activeHabits.length}</span>
            </div>
            <div class="rounded-xl border border-border bg-bg-card px-3 py-2">
              <div class="mb-1 flex items-center gap-1">
                <Flame size={10} class="text-accent-secondary" />
                <span class="text-[10px] font-mono uppercase tracking-wider text-muted">Streak</span>
              </div>
              <span class="text-base font-mono font-bold text-accent-secondary">{overallStreak}d</span>
            </div>
            <div class="rounded-xl border border-border bg-bg-card px-3 py-2">
              <div class="mb-1 flex items-center gap-1">
                <TrendingUp size={10} class="text-accent-secondary" />
                <span class="text-[10px] font-mono uppercase tracking-wider text-muted">Done</span>
              </div>
              <span class="text-base font-mono font-bold text-accent-secondary">{completedTodayCount}</span>
            </div>
          </div>
        </div>

        {#if todayRate >= 100}
          <div class="mt-3 flex items-center gap-3 rounded-xl border border-accent-secondary/30 bg-accent-secondary/5 px-4 py-2.5">
            <span class="text-lg" role="img" aria-label="celebration">🎉</span>
            <div>
              <p class="text-sm font-semibold text-foreground">Perfect day!</p>
              <p class="text-[11px] font-mono text-muted">All habits completed. Keep the streak alive!</p>
            </div>
          </div>
        {/if}
      </div>
    </div>

    <!-- Controls -->
    <div class="sticky top-0 z-10 border-b border-border bg-bg-primary/90 px-4 py-3 backdrop-blur-sm">
      <div class="mx-auto max-w-2xl">
        <div class="flex items-center gap-2">
          <!-- Filter tabs -->
          <div class="flex flex-1 gap-1 overflow-x-auto">
            {#each (['all', 'pending', 'done', 'archived'] as const) as f (f)}
              <button
                type="button"
                class="flex-shrink-0 rounded-lg px-3 py-1.5 text-[11px] font-mono uppercase tracking-wider transition {filter === f ? 'bg-accent/15 text-accent' : 'text-muted hover:text-foreground'}"
                onclick={() => { filter = f; }}
              >
                {f}
              </button>
            {/each}
          </div>
          <!-- Add habit -->
          <button
            type="button"
            class="flex-shrink-0 flex items-center justify-center w-8 h-8 rounded-full bg-accent text-bg-primary transition hover:opacity-90"
            aria-label="Add habit"
            onclick={navigateToNewHabit}
          >
            <Plus size={16} />
          </button>
        </div>
        <!-- Search -->
        <div class="relative mt-2">
          <Search size={13} class="absolute left-3 top-1/2 -translate-y-1/2 text-muted" />
          <input
            type="search"
            placeholder="Search habits..."
            bind:value={searchQuery}
            class="w-full rounded-xl border border-border bg-bg-secondary py-2 pl-8 pr-3 text-sm text-foreground placeholder:text-muted focus:border-accent focus:outline-none"
          />
        </div>
      </div>
    </div>

    <!-- Reminders panel (push notification opt-in) -->
    <RemindersPanel />

    <!-- Habit list -->
    <div class="mx-auto max-w-2xl px-4 py-3">
      {#if filteredHabits.length === 0}
        <div class="py-16 text-center text-muted">
          <p class="text-4xl mb-3">
            {filter === 'pending' ? '🎉' : filter === 'done' ? '✨' : filter === 'archived' ? '🗂️' : '👋'}
          </p>
          <p class="text-lg font-semibold text-foreground">
            {filter === 'pending' ? 'All done for today!' : filter === 'done' ? 'No completed habits yet' : filter === 'archived' ? 'No archived habits' : 'No habits found'}
          </p>
          {#if filter === 'all' && !searchQuery}
            <button
              type="button"
              onclick={navigateToNewHabit}
              class="mt-4 rounded-2xl bg-accent px-5 py-2 text-sm font-semibold uppercase tracking-widest text-bg-primary transition hover:opacity-90"
            >
              Add a habit
            </button>
          {/if}
        </div>
      {:else}
        <ul class="space-y-2">
          {#each filteredHabits as habit (habit.id)}
            {@const accent = HABIT_COLOR_THEMES[habit.color]}
            {@const target = Math.max(1, habit.dailyTarget ?? 1)}
            {@const todayCount = habit.completions[todayKey] ?? 0}
            {@const completed = todayCount >= target}
            {@const isFrozen = getScheduleStatusForDate(habit, todayDate) === 'frozen'}
            {@const isScheduled = getScheduleStatusForDate(habit, todayDate) === 'scheduled'}
            {@const streak = calculateScheduledStreak(habit, habit.completions).current}
            {@const completionRate = calculateScheduledCompletionRate(habit, habit.completions)}
            {@const last7 = buildLast7(habit, todayDate)}
            <li
              class="group relative transition-opacity {dragId && dragId !== habit.id ? 'opacity-60' : ''} {dragOverId === habit.id ? 'scale-[1.01]' : ''}"
              draggable={isDragActive()}
              ondragstart={(e) => isDragActive() && onDragStart(e, habit.id)}
              ondragover={(e) => isDragActive() && onDragOver(e, habit.id)}
              ondragleave={() => isDragActive() && onDragLeave()}
              ondrop={(e) => isDragActive() && void onDrop(e, habit.id)}
              ondragend={() => isDragActive() && onDragEnd()}
            >
              <div class="flex items-center gap-3 rounded-2xl border {dragOverId === habit.id ? 'border-accent/50' : 'border-border'} bg-bg-card px-4 py-3 transition hover:border-border-hover">
                <!-- Drag handle (only when reorder is possible) -->
                {#if isDragActive()}
                  <span class="flex-shrink-0 cursor-grab active:cursor-grabbing text-border/60 hover:text-muted transition-colors">
                    <GripVertical size={14} />
                  </span>
                {/if}
                <!-- Toggle button -->
                <button
                  type="button"
                  aria-label="{completed ? 'Undo' : 'Complete'} {habit.name}"
                  onclick={(e) => { e.stopPropagation(); void toggleHabit(habit); }}
                  class="relative flex-shrink-0 flex h-9 w-9 items-center justify-center rounded-full border-2 transition
                    {completed
                      ? `border-transparent`
                      : isScheduled
                        ? 'border-border-hover hover:border-muted'
                        : isFrozen
                          ? 'border-border bg-bg-secondary'
                          : 'border-dashed border-border/40 hover:border-border'}"
                  style={completed ? `background-color: ${accent.hex}22; border-color: ${accent.hex}66;` : ''}
                  disabled={isFrozen}
                >
                  {#if completed}
                    <svg viewBox="0 0 12 12" class="h-4 w-4" style="color: {accent.hex}">
                      <path d="M2 6l3 3 5-5" stroke="currentColor" stroke-width="1.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                  {:else if isFrozen}
                    <svg viewBox="0 0 12 12" class="h-3.5 w-3.5 text-muted">
                      <path d="M6 1v10M1 6h10M3 3l6 6M9 3l-6 6" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="round"/>
                    </svg>
                  {:else if target > 1}
                    <span class="text-[10px] font-mono" style="color: {accent.hex}">{todayCount}/{target}</span>
                  {/if}
                </button>

                <!-- Habit info (clickable) -->
                <button
                  type="button"
                  class="flex flex-1 items-center gap-3 text-left min-w-0"
                  onclick={() => navigateToDetail(habit.id)}
                >
                  <span class="text-xl leading-none flex-shrink-0">{habit.icon}</span>
                  <div class="min-w-0 flex-1">
                    <p class="truncate text-sm font-semibold text-foreground {completed ? 'opacity-60' : ''}">{habit.name}</p>
                    {#if habit.tags.length > 0}
                      <div class="mt-0.5 flex gap-1 flex-wrap">
                        {#each habit.tags.slice(0, 3) as tag (tag)}
                          <span class="rounded-full border border-border px-1.5 py-0.5 text-[10px] font-mono text-muted">{tag}</span>
                        {/each}
                      </div>
                    {/if}
                  </div>
                </button>

                <!-- Metrics (non-interactive) -->
                <div class="flex flex-shrink-0 items-center gap-2" aria-hidden="true">
                  {#if streak > 0}
                    <span class="hidden items-center gap-0.5 text-[10px] font-mono text-accent-secondary sm:flex">
                      <Flame size={10} />
                      {streak}
                    </span>
                  {/if}
                  <CompletionRing percentage={completionRate} size={26} strokeWidth={2.5} color={habit.color} showText={false} />
                  <div class="hidden sm:flex items-end gap-[2px] h-4">
                    {#each last7 as done, i (i)}
                      <div
                        class="w-[3px] rounded-sm transition-all"
                        style="height: {done ? '100%' : '30%'}; background-color: {done ? accent.hex : 'var(--border)'}; opacity: {0.4 + i * 0.09}"
                      ></div>
                    {/each}
                  </div>
                  <div class="hidden lg:block">
                    <MiniHeatmap completions={habit.completions} dailyTarget={habit.dailyTarget} color={habit.color} />
                  </div>
                </div>
              </div>
            </li>
          {/each}
        </ul>
      {/if}
    </div>
  </div>
{/if}
