// apps/web-svelte/src/lib/components/AuthGate.svelte
<script lang="ts">
  import { startOAuthLogin } from '$lib/auth/oauth';

  let { onHelp }: { onHelp?: () => void } = $props();
</script>

<div class="flex items-center justify-center min-h-screen p-4">
  <div class="w-full max-w-sm rounded-2xl border border-border bg-bg-card/80 backdrop-blur-lg p-8 text-center shadow-xl">
    <img
      src="/app-icon.svg"
      alt="Habbit Runner"
      class="w-16 h-16 mx-auto mb-4 rounded-2xl"
    />
    <h1 class="text-lg font-semibold text-foreground mb-1">Habbit Runner</h1>
    <p class="text-sm text-muted mb-6">Sign in to start tracking your habits</p>

    <button
      type="button"
      onclick={startOAuthLogin}
      class="w-full rounded-xl bg-accent px-4 py-3 text-sm font-semibold text-bg transition-all hover:opacity-90 active:scale-[0.98]"
    >
      Continue with Google
    </button>

    {#if onHelp}
      <button
        type="button"
        onclick={onHelp}
        class="mt-4 text-xs text-muted hover:text-foreground transition-colors"
      >
        Need help?
      </button>
    {/if}
  </div>
</div>

// packages/web/src/components/AuthGate.tsx
import React from 'react';
import { startOAuthLogin } from '@/lib/auth/oauth';

interface AuthGateProps {
  onError: (message: string) => void;
}

export function AuthGate({ onError }: AuthGateProps) {
  return (
    <div className="min-h-screen bg-bg-primary flex items-center justify-center px-4">
      <div className="w-full max-w-md border border-border rounded-2xl bg-bg-secondary p-6 text-foreground">
        <h1 className="text-xl font-semibold mb-2">Sign in to Habbit Runner</h1>
        <p className="text-sm text-muted mb-6">
          Sign in with Google to enable sync across your devices.
        </p>

        <div className="space-y-3">
          <button
            className="w-full rounded-lg border border-border-hover bg-bg-card px-4 py-2.5 text-sm font-medium hover:border-accent/40 hover:bg-accent/10 transition-colors"
            onClick={startOAuthLogin}
          >
            Continue with Google
          </button>
        </div>

        <button
          className="mt-4 text-xs text-muted hover:text-foreground"
          onClick={() =>
            onError('OAuth is not configured. Fill in packages/server/.env and restart the API.')
          }
        >
          Sign-in not working?
        </button>
      </div>
    </div>
  );
}
