// apps/web-svelte/src/lib/components/ChartGuideTooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  type TooltipVariant = 'bars' | 'line' | 'grid' | 'columns';

  let {
    title,
    subtitle,
    items = [],
    variant = 'bars',
    open = false,
    position,
    onClose,
    children
  }: {
    title?: string;
    subtitle?: string;
    items?: Array<{ label: string; value: string | number; color?: string }>;
    variant?: TooltipVariant;
    open?: boolean;
    position?: { x: number; y: number };
    onClose?: () => void;
    children?: Snippet;
  } = $props();

  function handleBackdropClick() {
    onClose?.();
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose?.();
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if open && position}
  <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-40" onclick={handleBackdropClick}></div>

  <div
    class="fixed z-50 min-w-[160px] max-w-[280px] rounded-xl border border-border bg-bg-card px-4 py-3 shadow-2xl"
    style="left: {Math.min(position.x, window.innerWidth - 300)}px; top: {Math.max(8, position.y - 20)}px;"
  >
    {#if title}
      <p class="text-xs font-semibold text-foreground mb-0.5">{title}</p>
    {/if}
    {#if subtitle}
      <p class="text-[10px] font-mono text-muted mb-2">{subtitle}</p>
    {/if}

    {#if variant === 'bars'}
      <div class="space-y-1.5">
        {#each items as item}
          <div class="flex items-center justify-between gap-2">
            <div class="flex items-center gap-1.5">
              {#if item.color}
                <span class="inline-block h-2 w-2 rounded-full" style="background-color: {item.color}"></span>
              {/if}
              <span class="text-[11px] text-foreground">{item.label}</span>
            </div>
            <span class="text-[11px] font-mono text-muted">{item.value}</span>
          </div>
        {/each}
      </div>
    {:else if variant === 'line'}
      <div class="space-y-1">
        {#each items as item}
          <div class="flex items-center justify-between gap-3">
            <span class="text-[11px] text-foreground truncate">{item.label}</span>
            <span class="text-[11px] font-mono text-muted">{item.value}</span>
          </div>
        {/each}
      </div>
    {:else if variant === 'grid'}
      <div class="grid grid-cols-2 gap-x-3 gap-y-1">
        {#each items as item}
          <div class="text-[11px] text-muted">{item.label}</div>
          <div class="text-[11px] font-mono text-foreground text-right">{item.value}</div>
        {/each}
      </div>
    {:else}
      <div class="flex gap-3">
        {#each items as item}
          <div class="flex flex-col items-center gap-0.5">
            {#if item.color}
              <div class="h-6 w-3 rounded-sm" style="background-color: {item.color}; opacity: 0.7"></div>
            {/if}
            <span class="text-[10px] text-muted">{item.label}</span>
            <span class="text-[10px] font-mono text-foreground">{item.value}</span>
          </div>
        {/each}
      </div>
    {/if}

    {#if children}
      <div class="mt-2 border-t border-border pt-2">
        {@render children()}
      </div>
    {/if}
  </div>
{/if}

// packages/web/src/components/ChartGuideTooltip.tsx
import { useState } from 'react';
import { BarChart3Icon, CircleHelpIcon, Grid2x2Icon, TrendingUpIcon } from 'lucide-react';

type ChartGuideVariant = 'bars' | 'line' | 'grid' | 'columns';

type ChartGuideTooltipProps = {
  title: string;
  summary: string;
  focusPoints: string[];
  variant?: ChartGuideVariant;
};

function GuideVisual({ variant }: { variant: ChartGuideVariant }) {
  if (variant === 'line') {
    return (
      <div className="relative h-20 overflow-hidden rounded-2xl border border-accent/20 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.14),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.06),rgba(255,255,255,0.01))] px-3 py-2">
        <div className="absolute inset-x-0 bottom-2 h-px bg-border/60" />
        <svg viewBox="0 0 96 56" className="relative z-10 h-full w-full">
          <polyline
            fill="none"
            stroke="var(--accent)"
            strokeWidth="3"
            strokeLinecap="round"
            strokeLinejoin="round"
            points="4,40 22,30 38,34 54,18 72,22 92,8"
          />
          {[['4', '40'], ['22', '30'], ['38', '34'], ['54', '18'], ['72', '22'], ['92', '8']].map(([x, y]) => (
            <circle key={`${x}-${y}`} cx={x} cy={y} r="3.5" fill="var(--bg-primary)" stroke="var(--accent)" strokeWidth="2" />
          ))}
        </svg>
        <div className="absolute left-3 top-3 rounded-full border border-accent/20 bg-accent/10 px-2 py-0.5 text-[9px] font-mono uppercase tracking-[0.2em] text-accent">
          trend
        </div>
      </div>
    );
  }

  if (variant === 'grid') {
    return (
      <div className="grid h-20 grid-cols-5 gap-1 rounded-2xl border border-accent/20 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.14),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.06),rgba(255,255,255,0.01))] p-3">
        {[0.14, 0.22, 0.42, 0.78, 0.3, 0.24, 0.56, 0.92, 0.48, 0.18, 0.12, 0.66, 0.28, 0.84, 0.34, 0.16, 0.38, 0.7, 0.5, 0.2].map((opacity, index) => (
          <div
            key={index}
            className="rounded-[6px] bg-accent"
            style={{ opacity }}
          />
        ))}
      </div>
    );
  }

  if (variant === 'columns') {
    return (
      <div className="flex h-20 items-end gap-1 rounded-2xl border border-accent/20 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.14),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.06),rgba(255,255,255,0.01))] p-3">
        {[24, 42, 32, 58, 50, 72, 46, 64].map((height, index) => (
          <div
            key={index}
            className="flex-1 rounded-t-md bg-accent"
            style={{ height, opacity: 0.28 + index * 0.08 }}
          />
        ))}
      </div>
    );
  }

  return (
    <div className="flex h-20 items-end gap-1 rounded-2xl border border-accent/20 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.14),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.06),rgba(255,255,255,0.01))] p-3">
      {[28, 44, 60, 38, 68].map((height, index) => (
        <div key={index} className="flex-1 rounded-t-md bg-accent" style={{ height, opacity: 0.35 + index * 0.1 }} />
      ))}
    </div>
  );
}

function renderVariantIcon(variant: ChartGuideVariant) {
  if (variant === 'line') {
    return <TrendingUpIcon size={14} />;
  }
  if (variant === 'grid') {
    return <Grid2x2Icon size={14} />;
  }
  return <BarChart3Icon size={14} />;
}

export function ChartGuideTooltip({
  title,
  summary,
  focusPoints,
  variant = 'bars'
}: ChartGuideTooltipProps) {
  const [isPinned, setIsPinned] = useState(false);
  const [isHovered, setIsHovered] = useState(false);
  const open = isPinned || isHovered;

  return (
    <div
      className="relative"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <button
        type="button"
        aria-label={`Explain ${title}`}
        aria-expanded={open}
        onClick={() => setIsPinned((prev) => !prev)}
        onBlur={(event) => {
          if (!event.currentTarget.parentElement?.contains(event.relatedTarget as Node | null)) {
            setIsPinned(false);
          }
        }}
        onKeyDown={(event) => {
          if (event.key === 'Escape') {
            setIsPinned(false);
          }
        }}
        className={`inline-flex h-8 w-8 items-center justify-center rounded-full border transition-colors ${
          open
            ? 'border-accent/50 bg-accent/10 text-accent'
            : 'border-border bg-bg-card text-muted hover:border-border-hover hover:text-foreground'
        }`}
      >
        <CircleHelpIcon size={14} strokeWidth={2.1} />
      </button>
      {open ? (
        <div className="absolute right-0 top-full z-40 mt-2 w-72 max-w-[calc(100vw-2rem)] rounded-3xl border border-border bg-bg-card/95 p-3 text-left shadow-[0_18px_60px_rgba(0,0,0,0.32)] backdrop-blur">
          <div className="mb-3 flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-2xl border border-accent/20 bg-accent/10 text-accent">
              {renderVariantIcon(variant)}
            </div>
            <div className="min-w-0">
              <p className="text-[9px] font-mono uppercase tracking-[0.22em] text-muted">Why it matters</p>
              <p className="truncate text-xs font-semibold text-foreground">{title}</p>
            </div>
          </div>
          <GuideVisual variant={variant} />
          <p className="mt-3 text-[11px] leading-5 text-foreground">{summary}</p>
          <div className="mt-3 rounded-2xl border border-border bg-bg-primary/60 px-3 py-2">
            <p className="text-[9px] font-mono uppercase tracking-[0.22em] text-muted">Watch for</p>
            <div className="mt-2 space-y-1.5">
              {focusPoints.map((point) => (
                <div key={point} className="flex items-start gap-2 text-[10px] font-mono text-muted">
                  <span className="mt-1 h-1.5 w-1.5 flex-none rounded-full bg-accent" />
                  <span>{point}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
