// apps/web/src/lib/components/DescriptionTooltip.svelte
<script lang="ts">
  import { portal } from '$lib/actions/portal';
  import { marked } from 'marked';
  import DOMPurify from 'dompurify';

  type Placement = 'above' | 'below';

  type Props = {
    description: string;
  };

  const { description }: Props = $props();

  const renderedDescription = $derived.by(() => {
    try {
      const html = marked.parse(description) as string;
      return DOMPurify.sanitize(html);
    } catch {
      return description;
    }
  });

  let show = $state(false);
  let ready = $state(false);
  let placement = $state<Placement>('above');
  let anchor = $state({ cx: 0, triggerTop: 0, triggerBottom: 0 });
  let triggerEl = $state<HTMLButtonElement | null>(null);
  let panelEl = $state<HTMLDivElement | null>(null);
  let closeTimer: ReturnType<typeof setTimeout> | null = null;
  let isHovering = $state(false);

  const isMobile = $derived.by(() => {
    if (typeof window === 'undefined') return false;
    return window.innerWidth < 640;
  });

  const panelWidth = $derived.by(() => {
    if (typeof window === 'undefined') {
      return 280;
    }
    if (isMobile) {
      return window.innerWidth - 32; // 16px padding on each side
    }
    return Math.min(Math.max(window.innerWidth / 3, 320), 480);
  });

  const left = $derived.by(() => {
    if (typeof window === 'undefined' || isMobile) {
      return 16; // For mobile, we use inset-x-0 instead
    }
    return Math.max(panelWidth / 2 + 12, Math.min(anchor.cx, window.innerWidth - panelWidth / 2 - 12));
  });

  const top = $derived(isMobile ? undefined : (placement === 'above' ? anchor.triggerTop - 10 : anchor.triggerBottom + 10));
  const transform = $derived(isMobile ? 'none' : (placement === 'above' ? 'translate(-50%, -100%)' : 'translate(-50%, 0)'));

  function clearCloseTimer() {
    if (closeTimer) {
      clearTimeout(closeTimer);
      closeTimer = null;
    }
  }

  function startCloseTimer() {
    clearCloseTimer();
    closeTimer = setTimeout(() => {
      if (!isHovering) {
        show = false;
      }
    }, 3000);
  }

  function open() {
    const el = triggerEl;
    if (!el) {
      return;
    }
    const rect = el.getBoundingClientRect();
    anchor = {
      cx: rect.left + rect.width / 2,
      triggerTop: rect.top,
      triggerBottom: rect.bottom
    };
    placement = 'above';
    ready = false;
    show = true;
    clearCloseTimer();
  }

  function close() {
    show = false;
    clearCloseTimer();
  }

  $effect(() => {
    if (!show || !panelEl || isMobile) {
      return;
    }
    const panelHeight = panelEl.offsetHeight;
    placement = anchor.triggerTop - panelHeight - 10 < 12 ? 'below' : 'above';
    ready = true;
  });

  // Handle touch events for mobile swipe-down to close
  let touchStartY = 0;
  function handleTouchStart(e: TouchEvent) {
    touchStartY = e.touches[0].clientY;
  }
  function handleTouchEnd(e: TouchEvent) {
    if (!isMobile) return;
    const touchEndY = e.changedTouches[0].clientY;
    const diff = touchEndY - touchStartY;
    // Swipe down more than 50px to close
    if (diff > 50) {
      show = false;
    }
  }

  // Cleanup timer on destroy
  $effect(() => {
    return () => {
      clearCloseTimer();
    };
  });
</script>

<button
  bind:this={triggerEl}
  type="button"
  class="inline-flex h-4 w-4 flex-shrink-0 cursor-help items-center justify-center rounded border border-dashed border-muted font-mono text-[9px] text-muted transition-colors hover:border-foreground hover:text-foreground"
  onmouseenter={() => {
    if (!show) {
      open();
    }
  }}
  onmouseleave={() => {
    // Start close timer when leaving trigger
    if (show && !isHovering) {
      startCloseTimer();
    }
  }}
  onclick={(e) => {
    e.stopPropagation();
    if (show) {
      close();
    } else {
      open();
    }
  }}
  aria-label="Description"
>
  ?
</button>

{#if show}
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  {#if isMobile}
    <!-- Mobile: full-screen modal at bottom with scroll -->
    <div
      use:portal
      bind:this={panelEl}
      class="fixed inset-x-0 bottom-0 z-[9999] max-h-[70vh] overflow-y-auto rounded-t-2xl border border-border/60 bg-bg-card shadow-[0_8px_32px_rgba(0,0,0,0.28)] backdrop-blur-sm"
      role="dialog"
      aria-label="Description"
      tabindex="-1"
      ontouchstart={handleTouchStart}
      ontouchend={handleTouchEnd}
      onclick={(e) => { e.stopPropagation(); }}
      onkeydown={(e) => {
        if (e.key === 'Escape') {
          show = false;
        }
      }}
    >
      <div class="flex justify-center pb-1 pt-2 cursor-grab active:cursor-grabbing" role="presentation" aria-hidden="true">
        <div class="h-[2px] w-8 rounded-full bg-foreground opacity-25"></div>
      </div>
      <div class="markdown-content break-words px-4 pb-6 text-[11px] leading-[1.6] text-foreground">{@html renderedDescription}</div>
    </div>
    <!-- Overlay to close on tap outside -->
    <div
      use:portal
      class="fixed inset-0 z-[9998] bg-black/20"
      onclick={() => { show = false; }}
      aria-hidden="true"
    ></div>
  {:else}
    <!-- Desktop: tooltip with 1/3 width -->
    <div
      use:portal
      bind:this={panelEl}
      class="fixed z-[9999]"
      style:left="{left}px"
      style:top="{top}px"
      style:transform={transform}
      style:width="{panelWidth}px"
      style:visibility={ready ? 'visible' : 'hidden'}
      style:max-height="60vh"
      style:overflow-y="auto"
      role="tooltip"
      tabindex="-1"
      onmouseenter={() => {
        isHovering = true;
        clearCloseTimer();
      }}
      onmouseleave={() => {
        isHovering = false;
        startCloseTimer();
      }}
      onclick={(e) => { e.stopPropagation(); }}
      onkeydown={(e) => {
        if (e.key === 'Escape') {
          close();
        }
      }}
    >
      <div class="overflow-hidden rounded-2xl border border-border/60 bg-bg-card shadow-[0_8px_32px_rgba(0,0,0,0.28)] backdrop-blur-sm">
        <div class="flex items-center justify-between px-3 pt-2 pb-1">
          <div class="flex justify-center flex-1">
            <div class="h-[2px] w-8 rounded-full bg-foreground opacity-25"></div>
          </div>
          <button
            type="button"
            class="ml-2 -mr-1 flex h-5 w-5 flex-shrink-0 items-center justify-center rounded hover:bg-foreground/10"
            onclick={() => { close(); }}
            aria-label="Close"
          >
            <span class="text-[10px] font-mono leading-none">✕</span>
          </button>
        </div>
        <div class="markdown-content break-words px-3 pb-3 text-[11px] leading-[1.6] text-foreground">{@html renderedDescription}</div>
      </div>
      <div
        class="absolute left-1/2 h-0 w-0 -translate-x-1/2"
        style={placement === 'above'
          ? 'bottom: 0; transform: translateX(-50%) translateY(100%); border-left: 6px solid transparent; border-right: 6px solid transparent; border-top: 6px solid color-mix(in srgb, var(--border) 60%, transparent);'
          : 'top: 0; transform: translateX(-50%) translateY(-100%); border-left: 6px solid transparent; border-right: 6px solid transparent; border-bottom: 6px solid color-mix(in srgb, var(--border) 60%, transparent);'}
        aria-hidden="true"
      ></div>
    </div>
  {/if}
{/if}

<style>
  :global(.markdown-content) {
    word-break: break-word;
  }
  :global(.markdown-content p) {
    margin: 0 0 0.4em;
  }
  :global(.markdown-content p:last-child) {
    margin-bottom: 0;
  }
  :global(.markdown-content ul),
  :global(.markdown-content ol) {
    margin: 0 0 0.4em;
    padding-left: 1.2em;
  }
  :global(.markdown-content li) {
    margin-bottom: 0.2em;
  }
  :global(.markdown-content code) {
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    padding: 0.1em 0.3em;
    border-radius: 3px;
    font-size: 0.95em;
  }
  :global(.markdown-content pre) {
    background: color-mix(in srgb, var(--accent) 8%, transparent);
    padding: 0.5em 0.7em;
    border-radius: 6px;
    overflow-x: auto;
    margin: 0.4em 0;
    font-size: 0.95em;
  }
  :global(.markdown-content pre code) {
    background: none;
    padding: 0;
  }
  :global(.markdown-content strong) {
    font-weight: 600;
  }
  :global(.markdown-content em) {
    font-style: italic;
  }
  :global(.markdown-content a) {
    color: var(--accent);
    text-decoration: underline;
  }
  :global(.markdown-content h1),
  :global(.markdown-content h2),
  :global(.markdown-content h3) {
    margin: 0.6em 0 0.3em;
    font-weight: 600;
    line-height: 1.3;
  }
  :global(.markdown-content h1) { font-size: 1.1em; }
  :global(.markdown-content h2) { font-size: 1.05em; }
  :global(.markdown-content h3) { font-size: 1em; }
  :global(.markdown-content blockquote) {
    border-left: 3px solid color-mix(in srgb, var(--accent) 40%, transparent);
    padding-left: 0.6em;
    margin: 0.4em 0;
    color: color-mix(in srgb, var(--foreground) 70%, transparent);
  }
</style>

// packages/web/src/components/DescriptionTooltip.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';

type Placement = 'above' | 'below';

export function DescriptionTooltip({ description }: { description: string }) {
  const [show, setShow] = useState(false);
  const [ready, setReady] = useState(false);
  const [placement, setPlacement] = useState<Placement>('above');
  const [anchor, setAnchor] = useState({ cx: 0, triggerTop: 0, triggerBottom: 0 });
  const triggerRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);

  const open = () => {
    if (!triggerRef.current) {
      return;
    }
    const r = triggerRef.current.getBoundingClientRect();
    setAnchor({ cx: r.left + r.width / 2, triggerTop: r.top, triggerBottom: r.bottom });
    setPlacement('above');
    setReady(false);
    setShow(true);
  };

  useLayoutEffect(() => {
    if (!show || !panelRef.current) {
      return;
    }
    const panelH = panelRef.current.offsetHeight;
    setPlacement(anchor.triggerTop - panelH - 10 < 12 ? 'below' : 'above');
    setReady(true);
  }, [show, anchor]);

  const panelWidth = typeof window !== 'undefined' ? Math.min(280, window.innerWidth - 24) : 280;
  const left = typeof window !== 'undefined'
    ? Math.max(panelWidth / 2 + 12, Math.min(anchor.cx, window.innerWidth - panelWidth / 2 - 12))
    : anchor.cx;
  const top = placement === 'above' ? anchor.triggerTop - 10 : anchor.triggerBottom + 10;
  const transform = placement === 'above' ? 'translate(-50%, -100%)' : 'translate(-50%, 0)';

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        className="inline-flex items-center justify-center text-[9px] text-muted hover:text-foreground cursor-help font-mono w-4 h-4 rounded border border-dashed border-muted hover:border-foreground transition-colors flex-shrink-0"
        onMouseEnter={() => { open(); }}
        onMouseLeave={() => setShow(false)}
        onClick={(e) => { e.stopPropagation(); if (show) { setShow(false); } else { open(); } }}
        aria-label="Описание"
      >
        ?
      </button>
      {show && createPortal(
        <div
          ref={panelRef}
          className="fixed z-[9999]"
          style={{ left, top, transform, width: panelWidth, visibility: ready ? 'visible' : 'hidden' }}
          onMouseEnter={() => setShow(true)}
          onMouseLeave={() => setShow(false)}
        >
          <div className="rounded-2xl border border-border/60 bg-bg-card shadow-[0_8px_32px_rgba(0,0,0,0.28)] backdrop-blur-sm overflow-hidden">
            <div className="flex justify-center pt-2 pb-1">
              <div className="h-[2px] w-8 rounded-full opacity-25 bg-foreground" />
            </div>
            <p className="px-3 pb-3 text-[11px] leading-[1.6] text-foreground whitespace-pre-wrap break-words">
              {description}
            </p>
          </div>
          <div
            className="absolute left-1/2 -translate-x-1/2 w-0 h-0"
            style={{
              ...(placement === 'above'
                ? { bottom: 0, transform: 'translateX(-50%) translateY(100%)', borderLeft: '6px solid transparent', borderRight: '6px solid transparent', borderTop: '6px solid color-mix(in srgb, var(--border) 60%, transparent)' }
                : { top: 0, transform: 'translateX(-50%) translateY(-100%)', borderLeft: '6px solid transparent', borderRight: '6px solid transparent', borderBottom: '6px solid color-mix(in srgb, var(--border) 60%, transparent)' }
              )
            }}
            aria-hidden
          />
        </div>,
        document.body
      )}
    </>
  );
}
