// packages/web/src/pages/Dashboard.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useHabits } from '@/hooks/useHabits';
import { useNavigate } from '@/lib/router';
import { useUndo } from '@/lib/undo';
import { formatAppDate } from '@/lib/i18n';
import type { Habit } from '@/types/habit';
import type { OnboardingTemplate } from '@/components/Onboarding';
import { DashboardView } from './components/DashboardView';

type Reminder = {
  habitId: string;
  time: string;
  message: string;
};

const parseReminderMinutes = (value: string): number | null => {
  const match = value.match(/^([01]\d|2[0-3]):([0-5]\d)$/);
  if (!match) {
    return null;
  }
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  return hours * 60 + minutes;
};

export function Dashboard() {
  const navigate = useNavigate();
  const { habits, setCompletionCount, addHabit, updateHabit, getTodayCompletionRate, formatDate } = useHabits();
  const [draggedHabitId, setDraggedHabitId] = useState<string | null>(null);
  const [dragOverHabitId, setDragOverHabitId] = useState<string | null>(null);
  const [dropHint, setDropHint] = useState<{ habitId: string; position: 'above' | 'below' } | null>(null);
  const reminderTracker = useRef<Record<string, string>>({});
  const reminderLastCheckRef = useRef<number | null>(null);
  const [reminders, setReminders] = useState<Reminder[]>([]);

  const sendBrowserNotification = useCallback((habit: Habit) => {
    if (typeof window === 'undefined' || !('Notification' in window) || Notification.permission !== 'granted') {
      return;
    }
    try {
      new Notification('Habbit reminder', {
        body: `Time for: ${habit.name}`,
        tag: `habit-reminder-${habit.id}`
      });
    } catch {
      // Ignore browsers that block notifications at runtime.
    }
  }, []);

  const applySortOrder = useCallback(
    async (orderedHabits: Habit[]) => {
      await Promise.all(
        orderedHabits.map((habit, index) => {
          const targetOrder = index;
          if (habit.sortOrder === targetOrder) {
            return Promise.resolve();
          }
          return updateHabit(habit.id, { sortOrder: targetOrder });
        })
      );
    },
    [updateHabit]
  );

  const handleDragStart = useCallback((event: React.DragEvent<HTMLDivElement>, habitId: string) => {
    event.dataTransfer?.setData('text/plain', habitId);
    event.dataTransfer?.setDragImage(new Image(), 0, 0);
    setDraggedHabitId(habitId);
    setDropHint(null);
  }, []);

  const handleDragOver = useCallback(
    (event: React.DragEvent<HTMLDivElement>, habitId: string) => {
      event.preventDefault();
      if (!draggedHabitId || draggedHabitId === habitId) {
        setDropHint(null);
        setDragOverHabitId(null);
        return;
      }
      const bounds = event.currentTarget.getBoundingClientRect();
      const midpoint = bounds.top + bounds.height / 2;
      const position = event.clientY < midpoint ? 'above' : 'below';
      setDropHint({ habitId, position });
      setDragOverHabitId(habitId);
    },
    [draggedHabitId]
  );

  const handleDrop = useCallback(
    async (event: React.DragEvent<HTMLDivElement>, habitId: string) => {
      event.preventDefault();
      if (!draggedHabitId || draggedHabitId === habitId) {
        setDragOverHabitId(null);
        setDraggedHabitId(null);
        return;
      }

      const original = [...habits];
      const sourceIndex = original.findIndex((habit) => habit.id === draggedHabitId);
      const targetIndex = original.findIndex((habit) => habit.id === habitId);
      if (sourceIndex === -1 || targetIndex === -1) {
        setDragOverHabitId(null);
        setDraggedHabitId(null);
        return;
      }

      const position =
        dropHint?.habitId === habitId
          ? dropHint.position
          : (() => {
              const bounds = event.currentTarget.getBoundingClientRect();
              const midpoint = bounds.top + bounds.height / 2;
              return event.clientY < midpoint ? 'above' : 'below';
            })();

      const ordered = [...original];
      const [moved] = ordered.splice(sourceIndex, 1);
      let insertIndex = targetIndex + (position === 'below' ? 1 : 0);
      if (sourceIndex < insertIndex) {
        insertIndex = Math.max(0, insertIndex - 1);
      }
      insertIndex = Math.max(0, Math.min(ordered.length, insertIndex));
      ordered.splice(insertIndex, 0, moved);
      await applySortOrder(ordered);

      setDragOverHabitId(null);
      setDraggedHabitId(null);
      setDropHint(null);
    },
    [applySortOrder, draggedHabitId, habits, dropHint]
  );

  const handleDragEnd = useCallback(() => {
    setDraggedHabitId(null);
    setDragOverHabitId(null);
    setDropHint(null);
  }, []);

  useEffect(() => {
    const checkReminders = () => {
      const nowTs = Date.now();
      const now = new Date(nowTs);
      const nowMinutes = now.getHours() * 60 + now.getMinutes();
      const nowDayKey = formatDate(now);
      const previousTs = reminderLastCheckRef.current ?? nowTs;
      reminderLastCheckRef.current = nowTs;
      const previous = new Date(previousTs);
      const previousMinutes = previous.getHours() * 60 + previous.getMinutes();
      const previousDayKey = formatDate(previous);

      habits.forEach((habit) => {
        if (!habit.reminderTime || habit.archived || habit.reminderEnabled === false) {return;}
        if (reminderTracker.current[habit.id] === nowDayKey) {return;}

        const reminderMinutes = parseReminderMinutes(habit.reminderTime);
        if (reminderMinutes === null) {return;}

        const crossedReminderTime =
          previousDayKey === nowDayKey
            ? reminderMinutes > previousMinutes && reminderMinutes <= nowMinutes
            : nowMinutes >= reminderMinutes;

        if (!crossedReminderTime) {return;}

        reminderTracker.current[habit.id] = nowDayKey;
        setReminders((prev) =>
          prev.some((item) => item.habitId === habit.id)
            ? prev
            : [
                ...prev,
                {
                  habitId: habit.id,
                  time: habit.reminderTime,
                  message: `Reminder: ${habit.name} (${habit.reminderTime})`
                }
              ]
        );
        sendBrowserNotification(habit);
      });
    };

    checkReminders();
    if (typeof window === 'undefined') {
      return;
    }

    const interval = window.setInterval(checkReminders, 30_000);
    const onVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        checkReminders();
      }
    };
    document.addEventListener('visibilitychange', onVisibilityChange);

    return () => {
      window.clearInterval(interval);
      document.removeEventListener('visibilitychange', onVisibilityChange);
    };
  }, [formatDate, habits, sendBrowserNotification]);

  useEffect(() => {
    setReminders((prev) => prev.filter((reminder) => habits.some((habit) => habit.id === reminder.habitId)));
  }, [habits]);

  const handleDismissReminder = useCallback((habitId: string) => {
    setReminders((prev) => prev.filter((reminder) => reminder.habitId !== habitId));
  }, []);

  const { push } = useUndo();
  const [addingTemplate, setAddingTemplate] = useState<string | null>(null);

  const handleTemplateSelect = useCallback(
    async (template: OnboardingTemplate) => {
      setAddingTemplate(template.name);
      try {
        const newId = await addHabit({
          name: template.name,
          description: template.description,
          icon: template.icon,
          color: template.color,
          tags: template.tags,
          frequency: template.frequency,
          customDays: template.customDays,
          targetStreak: template.targetStreak,
          dailyTarget: 1
        });
        navigate(`/habit/${newId}`);
      } finally {
        setAddingTemplate(null);
      }
    },
    [addHabit, navigate]
  );

  const [filter, setFilter] = useState<'all' | 'pending' | 'done'>('all');
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const today = formatDate(new Date());
  const todayRate = getTodayCompletionRate();
  const completedToday = habits.filter((h) => (h.completions[today] ?? 0) >= Math.max(1, h.dailyTarget ?? 1)).length;
  const totalActive = habits.length;
  const dateStr = formatAppDate(new Date(), { weekday: 'long', month: 'short', day: 'numeric' });

  const allTags = useMemo(() => {
    const tags = new Set<string>();
    habits.forEach((habit) => {
      habit.tags.forEach((tag) => tags.add(tag));
    });
    return Array.from(tags).sort();
  }, [habits]);

  const filtered = useMemo(() => {
    return habits.filter((h) => {
      if (filter === 'pending') {
        return (h.completions[today] ?? 0) < Math.max(1, h.dailyTarget ?? 1);
      }
      if (filter === 'done') {
        return (h.completions[today] ?? 0) >= Math.max(1, h.dailyTarget ?? 1);
      }
      if (selectedTags.length > 0 && !selectedTags.some((tag) => h.tags.includes(tag))) {
        return false;
      }
      return true;
    });
  }, [habits, filter, selectedTags, today]);

  const handleToggle = useCallback(
    async (habit: Habit) => {
      const target = Math.max(1, habit.dailyTarget ?? 1);
      const previousCount = habit.completions[today] ?? 0;
      const nextCount = previousCount >= target ? 0 : previousCount + 1;
      await setCompletionCount(habit.id, today, nextCount);
      push({
        message: nextCount >= target ? `Done: ${habit.name} (${nextCount}/${target})` : `Progress: ${habit.name} (${nextCount}/${target})`,
        actionLabel: 'Undo',
        onUndo: async () => {
          await setCompletionCount(habit.id, today, previousCount);
        }
      });
      handleDismissReminder(habit.id);
    },
    [push, setCompletionCount, today, handleDismissReminder]
  );

  const handleExport = useCallback(() => {
    if (typeof document === 'undefined' || habits.length === 0) {
      return;
    }
    const escape = (value: string) => `"${value.replace(/"/g, '""')}"`;
    const rows = habits.map((habit) => {
      const completionDates = Object.entries(habit.completions)
        .filter(([, count]) => count > 0)
        .map(([date, count]) => ({ date, count }));
      return [
        escape(habit.name),
        escape(habit.description),
        escape(habit.tags.join('|')),
        escape(JSON.stringify(completionDates))
      ].join(',');
    });
    const csv = ['name,description,tags,completions', ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `habits-export-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [habits]);

  const toggleTag = useCallback((tag: string) => {
    setSelectedTags((prev) => (prev.includes(tag) ? prev.filter((item) => item !== tag) : [...prev, tag]));
  }, []);

  let overallStreak = 0;
  const d = new Date();
  d.setDate(d.getDate() - 1);
  for (let i = 0; i < 30; i++) {
    const key = d.toISOString().split('T')[0];
    const allDone = habits.every((h) => (h.completions[key] ?? 0) >= Math.max(1, h.dailyTarget ?? 1));
    if (allDone) {
      overallStreak++;
      d.setDate(d.getDate() - 1);
    } else {
      break;
    }
  }

  return (
    <DashboardView
      habits={habits}
      filtered={filtered}
      reminders={reminders}
      dropHint={dropHint}
      dragOverHabitId={dragOverHabitId}
      filter={filter}
      allTags={allTags}
      selectedTags={selectedTags}
      addingTemplate={addingTemplate}
      today={today}
      todayRate={todayRate}
      completedToday={completedToday}
      totalActive={totalActive}
      dateStr={dateStr}
      overallStreak={overallStreak}
      setFilter={setFilter}
      setSelectedTags={setSelectedTags}
      toggleTag={toggleTag}
      navigate={navigate}
      handleExport={handleExport}
      handleTemplateSelect={handleTemplateSelect}
      handleToggle={handleToggle}
      handleDismissReminder={handleDismissReminder}
      handleDragStart={handleDragStart}
      handleDragOver={handleDragOver}
      handleDrop={handleDrop}
      handleDragEnd={handleDragEnd}
    />
  );
}

// apps/web-svelte/src/lib/pages/Dashboard.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { Plus } from 'lucide-svelte';
  import { habitsStore, toggleCompletion, updateHabit, getTodayCompletionRate } from '$lib/stores/habitsStore';
  import { undoStore } from '$lib/stores/undoStore';
  import { db, removePendingReminder, getPendingReminders } from '$lib/storage/db';
  import { formatDate } from '$lib/habits/habitStats';
  import { isMandatoryToday } from '$lib/habits/schedule';
  import { formatHabitLabel } from '$lib/habits/formatHabitLabel';
  import { filterAndSortHabits, calculateOverallStreak, getAllTags, exportHabitsCsv, reorderHabits } from '$lib/dashboard/dashboardHelpers';
  import type { DashboardFilter } from '$lib/dashboard/dashboardHelpers';
  import type { Habit } from '$lib/types/habit';
  import type { ViewDensity } from './dashboard/FilterBar.svelte';

  import DashboardHero from './dashboard/DashboardHero.svelte';
  import RemindersPanel from './dashboard/RemindersPanel.svelte';
  import FilterBar from './dashboard/FilterBar.svelte';
  import HabitListSection from './dashboard/HabitListSection.svelte';
  import Onboarding from '$lib/components/Onboarding.svelte';

  // --- State ---
  let filter = $state<DashboardFilter>('all');
  let searchQuery = $state('');
  let selectedTags = $state<string[]>([]);
  let sortMode = $state<'custom' | 'smart'>('custom');
  let viewDensity = $state<ViewDensity>('compact');
  let heroCollapsed = $state(false);

  // Reminders
  type Reminder = { id: string; habitId: string; time: string; message: string };
  let reminders = $state<Reminder[]>([]);

  // Drag-and-drop
  let draggedHabitId = $state<string | null>(null);
  let dragOverHabitId = $state<string | null>(null);
  let dropHintPosition = $state<'above' | 'below' | null>(null);

  // --- Derived from store ---
  const habits = $derived($habitsStore);
  const today = $derived(formatDate(new Date()));
  const todayDate = $derived.by(() => { const d = new Date(); d.setHours(0, 0, 0, 0); return d; });

  const activeHabits = $derived(habits.filter((h) => !h.archived));
  const totalActive = $derived(
    activeHabits.filter((h) => isMandatoryToday(h, todayDate)).length
  );
  const completedToday = $derived(
    activeHabits.filter((h) => {
      if (!isMandatoryToday(h, todayDate)) return false;
      const target = Math.max(1, h.dailyTarget ?? 1);
      return (h.completions[today] ?? 0) >= target;
    }).length
  );
  const todayRate = $derived(totalActive > 0 ? Math.round((completedToday / totalActive) * 100) : 0);
  const overallStreak = $derived(calculateOverallStreak(habits));
  const daysSinceLastCompletion = $derived.by(() => {
    let min = Infinity;
    for (const h of activeHabits) {
      const keys = Object.keys(h.completions).filter((k) => (h.completions[k] ?? 0) > 0).sort().reverse();
      if (keys.length > 0) {
        const diff = Math.floor((Date.now() - new Date(keys[0]).getTime()) / 86400000);
        if (diff < min) min = diff;
      }
    }
    return min === Infinity ? 0 : min;
  });

  const allTags = $derived(getAllTags(habits));
  const allCheckins = $derived.by(() => {
    const merged: Record<string, number> = {};
    for (const h of habits) {
      for (const [k, v] of Object.entries(h.completions)) {
        merged[k] = (merged[k] ?? 0) + v;
      }
    }
    return merged;
  });

  const filteredHabits = $derived(
    filterAndSortHabits(habits, filter, searchQuery, selectedTags, sortMode, today)
  );

  const dateStr = $derived(
    new Date().toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
  );

  const showOnboarding = $derived(habits.length === 0);

  // --- Reminder tracker ---
  $effect(() => {
    let interval: ReturnType<typeof setInterval> | undefined;

    async function checkReminders() {
      const pending = await getPendingReminders();
      reminders = pending.map((r) => ({
        id: r.id,
        habitId: r.habitId,
        time: r.time,
        message: r.message
      }));
    }

    void checkReminders();
    interval = setInterval(() => void checkReminders(), 30_000);

    const onVisibility = () => { if (document.visibilityState === 'visible') void checkReminders(); };
    document.addEventListener('visibilitychange', onVisibility);

    return () => {
      clearInterval(interval);
      document.removeEventListener('visibilitychange', onVisibility);
    };
  });

  // --- Handlers ---
  async function handleToggle(habit: Habit) {
    const result = await toggleCompletion(habit.id, today);
    if (result?.undo) {
      undoStore.push({
        label: `${formatHabitLabel(habit)} ${result.newCompleted ? 'completed' : 'undone'}`,
        execute: result.undo
      });
    }
  }

  function handleDetail(habit: Habit) {
    void goto(`/habit/${habit.id}`);
  }

  function handleExport() {
    exportHabitsCsv(habits);
  }

  function handleDismissReminder(reminderId: string) {
    void removePendingReminder(reminderId);
    reminders = reminders.filter((r) => r.id !== reminderId);
  }

  async function handleDisableReminder(habit: Habit) {
    await updateHabit(habit.id, { reminderTime: undefined });
    reminders = reminders.filter((r) => r.habitId !== habit.id);
  }

  function handleNavigateAdd() {
    void goto('/habit/new');
  }

  // --- Drag and Drop (desktop) ---
  function handleDragStart(habit: Habit, e: DragEvent) {
    if (sortMode !== 'custom') return;
    draggedHabitId = habit.id;
    if (e.dataTransfer) {
      e.dataTransfer.effectAllowed = 'move';
      e.dataTransfer.setData('text/plain', habit.id);
    }
  }

  function handleDragOver(habit: Habit, e: DragEvent) {
    if (!draggedHabitId || habit.id === draggedHabitId || sortMode !== 'custom') return;
    e.preventDefault();
    dragOverHabitId = habit.id;
    const el = (e.currentTarget as HTMLElement).closest('[data-habit-id]');
    if (!el) return;
    const rect = el.getBoundingClientRect();
    dropHintPosition = e.clientY < rect.top + rect.height / 2 ? 'above' : 'below';
  }

  function handleDrop(targetHabit: Habit, e: DragEvent) {
    e.preventDefault();
    if (!draggedHabitId || draggedHabitId === targetHabit.id || sortMode !== 'custom') return;
    const ordered = filteredHabits.filter((h) => !h.archived);
    void reorderHabits(ordered, draggedHabitId, targetHabit.id, dropHintPosition ?? 'below', db);
    resetDrag();
  }

  function handleDragEnd() {
    resetDrag();
  }

  function resetDrag() {
    draggedHabitId = null;
    dragOverHabitId = null;
    dropHintPosition = null;
  }

  // --- Touch drag ---
  let touchGhostEl: HTMLDivElement | undefined = $state();
  let touchStartY = 0;
  let touchCurrentHabitId: string | null = null;

  function handleTouchStart(habit: Habit, e: TouchEvent) {
    if (sortMode !== 'custom') return;
    touchCurrentHabitId = habit.id;
    draggedHabitId = habit.id;
    const touch = e.touches[0];
    touchStartY = touch.clientY;

    // Create ghost element
    const targetEl = (e.currentTarget as HTMLElement).closest('[data-habit-id]');
    if (!targetEl) return;
    const ghost = document.createElement('div');
    ghost.className = 'fixed z-[200] pointer-events-none opacity-80 rounded-xl border border-accent shadow-2xl bg-bg-secondary';
    const rect = targetEl.getBoundingClientRect();
    ghost.style.width = `${rect.width}px`;
    ghost.style.height = `${rect.height}px`;
    ghost.style.left = `${rect.left}px`;
    ghost.style.top = `${rect.top}px`;
    ghost.textContent = habit.name;
    ghost.style.display = 'flex';
    ghost.style.alignItems = 'center';
    ghost.style.justifyContent = 'center';
    ghost.style.fontSize = '14px';
    ghost.style.fontWeight = '600';
    document.body.appendChild(ghost);
    touchGhostEl = ghost;

    const onTouchMove = (ev: TouchEvent) => {
      ev.preventDefault();
      const t = ev.touches[0];
      if (touchGhostEl) {
        touchGhostEl.style.top = `${t.clientY - 24}px`;
      }
      // Determine drop target
      const elBelow = document.elementFromPoint(t.clientX, t.clientY);
      const habitEl = elBelow?.closest('[data-habit-id]') as HTMLElement | null;
      if (habitEl) {
        const id = habitEl.dataset.habitId ?? null;
        dragOverHabitId = id !== touchCurrentHabitId ? id : null;
        if (dragOverHabitId) {
          const r = habitEl.getBoundingClientRect();
          dropHintPosition = t.clientY < r.top + r.height / 2 ? 'above' : 'below';
        }
      }
    };

    const onTouchEnd = () => {
      if (dragOverHabitId && touchCurrentHabitId && touchCurrentHabitId !== dragOverHabitId) {
        const ordered = filteredHabits.filter((h) => !h.archived);
        void reorderHabits(ordered, touchCurrentHabitId, dragOverHabitId, dropHintPosition ?? 'below', db);
      }
      if (touchGhostEl) {
        touchGhostEl.remove();
        touchGhostEl = undefined;
      }
      resetDrag();
      touchCurrentHabitId = null;
      document.removeEventListener('touchmove', onTouchMove);
      document.removeEventListener('touchend', onTouchEnd);
    };

    document.addEventListener('touchmove', onTouchMove, { passive: false });
    document.addEventListener('touchend', onTouchEnd);
  }

  async function handleTemplateSelect(habits: Array<{ name: string; icon: string; type: string; frequency: string; tags: string[] }>) {
    const { addHabit } = await import('$lib/stores/habitsStore');
    for (const tmpl of habits) {
      await addHabit({
        name: tmpl.name,
        icon: tmpl.icon,
        type: (tmpl.type ?? 'boolean') as 'boolean' | 'numeric' | 'negative',
        frequency: (tmpl.frequency ?? 'daily') as 'daily' | 'weekly' | 'custom',
        tags: tmpl.tags ?? [],
        color: 'indigo'
      });
    }
  }
</script>

<div class="min-h-screen bg-bg-primary">
  {#if showOnboarding}
    <div class="flex items-center justify-center min-h-screen px-4">
      <Onboarding onTemplateSelect={handleTemplateSelect} />
    </div>
  {:else}
    <DashboardHero
      {dateStr}
      {todayRate}
      {completedToday}
      {totalActive}
      {overallStreak}
      {daysSinceLastCompletion}
      onExport={handleExport}
      bind:heroCollapsed
    />

    <RemindersPanel
      {reminders}
      habits={activeHabits}
      onToggle={handleToggle}
      onDismissReminder={handleDismissReminder}
      onDisableReminder={handleDisableReminder}
    />

    <FilterBar
      bind:filter
      {allTags}
      bind:selectedTags
      habits={activeHabits}
      today={today}
      bind:sortMode
      bind:viewDensity
      bind:searchQuery
    />

    <HabitListSection
      {filteredHabits}
      {filter}
      {viewDensity}
      {sortMode}
      {allCheckins}
      {draggedHabitId}
      {dragOverHabitId}
      {dropHintPosition}
      onToggle={handleToggle}
      onDetail={handleDetail}
      onDragStart={handleDragStart}
      onDragOver={handleDragOver}
      onDrop={handleDrop}
      onDragEnd={handleDragEnd}
      onTouchStart={handleTouchStart}
      onNavigateAdd={handleNavigateAdd}
    />

    <!-- FAB -->
    <a
      href="/habit/new"
      class="fixed bottom-20 right-6 z-50 w-12 h-12 rounded-full bg-accent text-bg-primary shadow-lg flex items-center justify-center hover:bg-accent/90 transition-colors"
      aria-label="Add new habit"
    >
      <Plus size={22} />
    </a>
  {/if}
</div>
