// apps/web/src/routes/(protected)/dashboard/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { resolve } from '$app/paths';
  import { Flame, Plus, Search, Zap, TrendingUp, GripVertical } from 'lucide-svelte';
  import CompletionRing from '$lib/components/CompletionRing.svelte';
  import MiniHeatmap from '$lib/components/MiniHeatmap.svelte';
  import Onboarding from '$lib/components/Onboarding.svelte';
  import RemindersPanel from '$lib/components/RemindersPanel.svelte';
  import type { OnboardingTemplate } from '$lib/components/onboarding';
  import { formatAppDate } from '@/lib/i18n';
  import { calculateScheduledCompletionRate, calculateScheduledStreak, getScheduleStatusForDate } from '$lib/habits/schedule';
  import { formatDate } from '$lib/habits/habitStats';
  import { habitsStore } from '$lib/stores/habits';
  import { HABIT_COLOR_THEMES } from '$lib/theme/habit-colors';
  import type { Habit } from '@/types/habit';

  type DashboardFilter = 'all' | 'pending' | 'done' | 'archived';

  let addingTemplate = $state<string | null>(null);
  let filter = $state<DashboardFilter>('all');
  let searchQuery = $state('');

  const todayDate = $derived.by(() => { const n = new Date(); return new Date(n.getFullYear(), n.getMonth(), n.getDate()); });
  const todayKey = $derived(formatDate(todayDate));
  const dateStr = $derived(formatAppDate(todayDate, { weekday: 'long', month: 'short', day: 'numeric' }));

  const activeHabits = $derived($habitsStore.habits);

  const scheduledToday = $derived(
    activeHabits.filter((h) => getScheduleStatusForDate(h, todayDate) === 'scheduled')
  );

  const completedTodayCount = $derived(
    scheduledToday.filter((h) => {
      const target = Math.max(1, h.dailyTarget ?? 1);
      return (h.completions[todayKey] ?? 0) >= target;
    }).length
  );

  const todayRate = $derived(
    scheduledToday.length > 0 ? Math.round((completedTodayCount / scheduledToday.length) * 100) : 0
  );

  const overallStreak = $derived.by(() => {
    if (activeHabits.length === 0) { return 0; }
    return Math.max(...activeHabits.map((h) => calculateScheduledStreak(h, h.completions).current));
  });

  const filteredHabits = $derived.by(() => {
    let list: Habit[];
    switch (filter) {
      case 'pending':
        list = activeHabits.filter((h) => {
          const target = Math.max(1, h.dailyTarget ?? 1);
          return (h.completions[todayKey] ?? 0) < target;
        });
        break;
      case 'done':
        list = activeHabits.filter((h) => {
          const target = Math.max(1, h.dailyTarget ?? 1);
          return (h.completions[todayKey] ?? 0) >= target;
        });
        break;
      case 'archived':
        list = $habitsStore.allHabits.filter((h) => h.archived);
        break;
      default:
        list = activeHabits;
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      list = list.filter(
        (h) =>
          h.name.toLowerCase().includes(q) ||
          h.tags.some((t) => t.toLowerCase().includes(q))
      );
    }
    return list;
  });

  function buildLast7(habit: Habit, todayStart: Date) {
    return Array.from({ length: 7 }, (_, i) => {
      const key = formatDate(new Date(todayStart.getTime() + (i - 6) * 86_400_000));
      const target = Math.max(1, habit.dailyTarget ?? 1);
      return (habit.completions[key] ?? 0) >= target;
    });
  }

  async function toggleHabit(habit: Habit) {
    await habitsStore.advanceCompletionCount(habit.id, todayKey);
  }

  function navigateToDetail(habitId: string) {
    void goto(resolve('/(protected)/habit/[id]', { id: habitId }));
  }

  function navigateToNewHabit() {
    void goto(resolve<'/(protected)/habit/new'>('/(protected)/habit/new', {}));
  }

  // Drag-and-drop reorder (only in 'all' view with no search)
  let dragId = $state<string | null>(null);
  let dragOverId = $state<string | null>(null);

  function isDragActive() {
    return filter === 'all' && !searchQuery.trim();
  }

  function onDragStart(e: DragEvent, habitId: string) {
    dragId = habitId;
    e.dataTransfer!.effectAllowed = 'move';
    e.dataTransfer!.setData('text/plain', habitId);
  }

  function onDragOver(e: DragEvent, habitId: string) {
    e.preventDefault();
    e.dataTransfer!.dropEffect = 'move';
    if (habitId !== dragId) dragOverId = habitId;
  }

  function onDragLeave() {
    dragOverId = null;
  }

  async function onDrop(e: DragEvent, targetId: string) {
    e.preventDefault();
    dragOverId = null;
    if (!dragId || dragId === targetId) { dragId = null; return; }
    const items = [...filteredHabits];
    const fromIdx = items.findIndex((h) => h.id === dragId);
    const toIdx = items.findIndex((h) => h.id === targetId);
    if (fromIdx < 0 || toIdx < 0) { dragId = null; return; }
    items.splice(toIdx, 0, items.splice(fromIdx, 1)[0]);
    const step = 1_000;
    const base = Date.now();
    for (let i = 0; i < items.length; i++) {
      const newOrder = base + i * step;
      if (items[i].sortOrder !== newOrder) {
        void habitsStore.updateHabit(items[i].id, { sortOrder: newOrder });
      }
    }
    dragId = null;
  }

  function onDragEnd() {
    dragId = null;
    dragOverId = null;
  }

  async function handleTemplateSelect(template: OnboardingTemplate) {
    addingTemplate = template.name;
    try {
      const allHabits = $habitsStore.allHabits;
      const sortOrder =
        allHabits.length > 0
          ? Math.max(...allHabits.map((h) => h.sortOrder ?? 0)) + 1
          : 0;
      const habitId = await habitsStore.addHabit({
        name: template.name,
        description: template.description,
        icon: template.icon,
        color: template.color,
        tags: template.tags,
        frequency: template.frequency,
        customDays: template.customDays,
        targetStreak: template.targetStreak,
        dailyTarget: 1,
        type: 'positive',
        freezeDays: [],
        archived: false,
        sortOrder
      });
      await goto(resolve('/(protected)/habit/[id]', { id: habitId }));
    } finally {
      addingTemplate = null;
    }
  }
</script>

<svelte:head>
  <title>Dashboard - Habbit Runner</title>
</svelte:head>

{#if $habitsStore.habits.length === 0}
  <Onboarding onCreateCustom={navigateToNewHabit} onTemplateSelect={handleTemplateSelect} activeTemplate={addingTemplate} />
{:else}
  <div class="min-h-screen bg-bg-primary">
    <!-- Hero -->
    <div class="border-b border-border bg-bg-secondary/50 px-4 py-4 backdrop-blur-sm">
      <div class="mx-auto max-w-2xl">
        <p class="text-[11px] font-mono uppercase tracking-widest text-muted">{dateStr}</p>
        <div class="mt-3 flex items-center gap-4">
          <CompletionRing percentage={todayRate} size={52} strokeWidth={4} showText={true} />
          <div class="grid flex-1 grid-cols-3 gap-2">
            <div class="rounded-xl border border-border bg-bg-card px-3 py-2">
              <div class="mb-1 flex items-center gap-1">
                <Zap size={10} class="text-accent" />
                <span class="text-[10px] font-mono uppercase tracking-wider text-muted">Active</span>
              </div>
              <span class="text-base font-mono font-bold text-foreground">{activeHabits.length}</span>
            </div>
            <div class="rounded-xl border border-border bg-bg-card px-3 py-2">
              <div class="mb-1 flex items-center gap-1">
                <Flame size={10} class="text-accent-secondary" />
                <span class="text-[10px] font-mono uppercase tracking-wider text-muted">Streak</span>
              </div>
              <span class="text-base font-mono font-bold text-accent-secondary">{overallStreak}d</span>
            </div>
            <div class="rounded-xl border border-border bg-bg-card px-3 py-2">
              <div class="mb-1 flex items-center gap-1">
                <TrendingUp size={10} class="text-accent-secondary" />
                <span class="text-[10px] font-mono uppercase tracking-wider text-muted">Done</span>
              </div>
              <span class="text-base font-mono font-bold text-accent-secondary">{completedTodayCount}</span>
            </div>
          </div>
        </div>

        {#if todayRate >= 100}
          <div class="mt-3 flex items-center gap-3 rounded-xl border border-accent-secondary/30 bg-accent-secondary/5 px-4 py-2.5">
            <span class="text-lg" role="img" aria-label="celebration">🎉</span>
            <div>
              <p class="text-sm font-semibold text-foreground">Perfect day!</p>
              <p class="text-[11px] font-mono text-muted">All habits completed. Keep the streak alive!</p>
            </div>
          </div>
        {/if}
      </div>
    </div>

    <!-- Controls -->
    <div class="sticky top-0 z-10 border-b border-border bg-bg-primary/90 px-4 py-3 backdrop-blur-sm">
      <div class="mx-auto max-w-2xl">
        <div class="flex items-center gap-2">
          <!-- Filter tabs -->
          <div class="flex flex-1 gap-1 overflow-x-auto">
            {#each (['all', 'pending', 'done', 'archived'] as const) as f (f)}
              <button
                type="button"
                class="flex-shrink-0 rounded-lg px-3 py-1.5 text-[11px] font-mono uppercase tracking-wider transition {filter === f ? 'bg-accent/15 text-accent' : 'text-muted hover:text-foreground'}"
                onclick={() => { filter = f; }}
              >
                {f}
              </button>
            {/each}
          </div>
          <!-- Add habit -->
          <button
            type="button"
            class="flex-shrink-0 flex items-center justify-center w-8 h-8 rounded-full bg-accent text-bg-primary transition hover:opacity-90"
            aria-label="Add habit"
            onclick={navigateToNewHabit}
          >
            <Plus size={16} />
          </button>
        </div>
        <!-- Search -->
        <div class="relative mt-2">
          <Search size={13} class="absolute left-3 top-1/2 -translate-y-1/2 text-muted" />
          <input
            type="search"
            placeholder="Search habits..."
            bind:value={searchQuery}
            class="w-full rounded-xl border border-border bg-bg-secondary py-2 pl-8 pr-3 text-sm text-foreground placeholder:text-muted focus:border-accent focus:outline-none"
          />
        </div>
      </div>
    </div>

    <!-- Reminders panel (push notification opt-in) -->
    <RemindersPanel />

    <!-- Habit list -->
    <div class="mx-auto max-w-2xl px-4 py-3">
      {#if filteredHabits.length === 0}
        <div class="py-16 text-center text-muted">
          <p class="text-4xl mb-3">
            {filter === 'pending' ? '🎉' : filter === 'done' ? '✨' : filter === 'archived' ? '🗂️' : '👋'}
          </p>
          <p class="text-lg font-semibold text-foreground">
            {filter === 'pending' ? 'All done for today!' : filter === 'done' ? 'No completed habits yet' : filter === 'archived' ? 'No archived habits' : 'No habits found'}
          </p>
          {#if filter === 'all' && !searchQuery}
            <button
              type="button"
              onclick={navigateToNewHabit}
              class="mt-4 rounded-2xl bg-accent px-5 py-2 text-sm font-semibold uppercase tracking-widest text-bg-primary transition hover:opacity-90"
            >
              Add a habit
            </button>
          {/if}
        </div>
      {:else}
        <ul class="space-y-2">
          {#each filteredHabits as habit (habit.id)}
            {@const accent = HABIT_COLOR_THEMES[habit.color]}
            {@const target = Math.max(1, habit.dailyTarget ?? 1)}
            {@const todayCount = habit.completions[todayKey] ?? 0}
            {@const completed = todayCount >= target}
            {@const isFrozen = getScheduleStatusForDate(habit, todayDate) === 'frozen'}
            {@const isScheduled = getScheduleStatusForDate(habit, todayDate) === 'scheduled'}
            {@const streak = calculateScheduledStreak(habit, habit.completions).current}
            {@const completionRate = calculateScheduledCompletionRate(habit, habit.completions)}
            {@const last7 = buildLast7(habit, todayDate)}
            <li
              class="group relative transition-opacity {dragId && dragId !== habit.id ? 'opacity-60' : ''} {dragOverId === habit.id ? 'scale-[1.01]' : ''}"
              draggable={isDragActive()}
              ondragstart={(e) => isDragActive() && onDragStart(e, habit.id)}
              ondragover={(e) => isDragActive() && onDragOver(e, habit.id)}
              ondragleave={() => isDragActive() && onDragLeave()}
              ondrop={(e) => isDragActive() && void onDrop(e, habit.id)}
              ondragend={() => isDragActive() && onDragEnd()}
            >
              <div class="flex items-center gap-3 rounded-2xl border {dragOverId === habit.id ? 'border-accent/50' : 'border-border'} bg-bg-card px-4 py-3 transition hover:border-border-hover">
                <!-- Drag handle (only when reorder is possible) -->
                {#if isDragActive()}
                  <span class="flex-shrink-0 cursor-grab active:cursor-grabbing text-border/60 hover:text-muted transition-colors">
                    <GripVertical size={14} />
                  </span>
                {/if}
                <!-- Toggle button -->
                <button
                  type="button"
                  aria-label="{completed ? 'Undo' : 'Complete'} {habit.name}"
                  onclick={(e) => { e.stopPropagation(); void toggleHabit(habit); }}
                  class="relative flex-shrink-0 flex h-9 w-9 items-center justify-center rounded-full border-2 transition
                    {completed
                      ? `border-transparent`
                      : isScheduled
                        ? 'border-border-hover hover:border-muted'
                        : isFrozen
                          ? 'border-border bg-bg-secondary'
                          : 'border-dashed border-border/40 hover:border-border'}"
                  style={completed ? `background-color: ${accent.hex}22; border-color: ${accent.hex}66;` : ''}
                  disabled={isFrozen}
                >
                  {#if completed}
                    <svg viewBox="0 0 12 12" class="h-4 w-4" style="color: {accent.hex}">
                      <path d="M2 6l3 3 5-5" stroke="currentColor" stroke-width="1.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                  {:else if isFrozen}
                    <svg viewBox="0 0 12 12" class="h-3.5 w-3.5 text-muted">
                      <path d="M6 1v10M1 6h10M3 3l6 6M9 3l-6 6" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="round"/>
                    </svg>
                  {:else if target > 1}
                    <span class="text-[10px] font-mono" style="color: {accent.hex}">{todayCount}/{target}</span>
                  {/if}
                </button>

                <!-- Habit info (clickable) -->
                <button
                  type="button"
                  class="flex flex-1 items-center gap-3 text-left min-w-0"
                  onclick={() => navigateToDetail(habit.id)}
                >
                  <span class="text-xl leading-none flex-shrink-0">{habit.icon}</span>
                  <div class="min-w-0 flex-1">
                    <p class="truncate text-sm font-semibold text-foreground {completed ? 'opacity-60' : ''}">{habit.name}</p>
                    {#if habit.tags.length > 0}
                      <div class="mt-0.5 flex gap-1 flex-wrap">
                        {#each habit.tags.slice(0, 3) as tag (tag)}
                          <span class="rounded-full border border-border px-1.5 py-0.5 text-[10px] font-mono text-muted">{tag}</span>
                        {/each}
                      </div>
                    {/if}
                  </div>
                </button>

                <!-- Metrics (non-interactive) -->
                <div class="flex flex-shrink-0 items-center gap-2" aria-hidden="true">
                  {#if streak > 0}
                    <span class="hidden items-center gap-0.5 text-[10px] font-mono text-accent-secondary sm:flex">
                      <Flame size={10} />
                      {streak}
                    </span>
                  {/if}
                  <CompletionRing percentage={completionRate} size={26} strokeWidth={2.5} color={habit.color} showText={false} />
                  <div class="hidden sm:flex items-end gap-[2px] h-4">
                    {#each last7 as done, i (i)}
                      <div
                        class="w-[3px] rounded-sm transition-all"
                        style="height: {done ? '100%' : '30%'}; background-color: {done ? accent.hex : 'var(--border)'}; opacity: {0.4 + i * 0.09}"
                      ></div>
                    {/each}
                  </div>
                  <div class="hidden lg:block">
                    <MiniHeatmap completions={habit.completions} dailyTarget={habit.dailyTarget} color={habit.color} />
                  </div>
                </div>
              </div>
            </li>
          {/each}
        </ul>
      {/if}
    </div>
  </div>
{/if}

// src/pages/Dashboard.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  BellRingIcon,
  CheckIcon,
  ChevronRightIcon,
  FlameIcon,
  GripVerticalIcon,
  TrendingUpIcon,
  ZapIcon
} from 'lucide-react';
import { CompletionRing } from '@/components/CompletionRing';
import { MiniHeatmap } from '@/components/MiniHeatmap';
import type { Habit } from '@/types/habit';
import { useHabits } from '@/hooks/useHabits';
import { HABIT_COLOR_THEMES } from '@/lib/theme/habit-colors';
import { useNavigate } from '@/lib/router';
import { Onboarding, type OnboardingTemplate } from '@/components/Onboarding';
import { useUndo } from '@/lib/undo';
import { formatAppDate } from '@/lib/i18n';

type Reminder = {
  habitId: string;
  time: string;
  message: string;
};

const parseReminderMinutes = (value: string): number | null => {
  const match = value.match(/^([01]\d|2[0-3]):([0-5]\d)$/);
  if (!match) {
    return null;
  }
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  return hours * 60 + minutes;
};
type HabitRowProps = {
  habit: Habit;
  onToggle: () => void;
  onDetail: () => void;
  onDragStart?: (event: React.DragEvent<HTMLDivElement>) => void;
  onDragOver?: (event: React.DragEvent<HTMLDivElement>) => void;
  onDrop?: (event: React.DragEvent<HTMLDivElement>) => void;
  onDragEnd?: () => void;
  isDropTarget?: boolean;
};

function HabitRow({
  habit,
  onToggle,
  onDetail,
  onDragStart,
  onDragOver,
  onDrop,
  onDragEnd,
  isDropTarget
}: HabitRowProps) {
  const today = new Date().toISOString().split('T')[0];
  const completed = !!habit.completions[today];
  const accent = HABIT_COLOR_THEMES[habit.color];
  // Calculate current streak
  let streak = 0;
  const d = new Date();
  for (let i = 0; i < 366; i++) {
    const key = d.toISOString().split('T')[0];
    if (!habit.completions[key]) {
      break;
    }
    streak++;
    d.setDate(d.getDate() - 1);
  }
  // Last 7 days mini bars
  const last7 = Array.from(
    {
      length: 7
    },
    (_, i) => {
      const date = new Date();
      date.setDate(date.getDate() - (6 - i));
      return !!habit.completions[date.toISOString().split('T')[0]];
    }
  );
  // Completion rate last 30 days
  let rate30 = 0;
  for (let i = 0; i < 30; i++) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    if (habit.completions[date.toISOString().split('T')[0]]) {rate30++;}
  }
  const completionRate = Math.round(rate30 / 30 * 100);
  return (
    <div
      draggable={Boolean(onDragStart)}
      onDragStart={onDragStart}
      onDragOver={onDragOver}
      onDrop={onDrop}
      onDragEnd={onDragEnd}
      tabIndex={0}
      role="listitem"
      aria-label={`${habit.name}, ${completed ? 'completed' : 'not completed'}`}
      onKeyDown={(event) => {
        if (event.key === 'Enter') {
          event.preventDefault();
          onDetail();
          return;
        }
        if (event.key === ' ') {
          event.preventDefault();
          onToggle();
        }
      }}
      className={`group flex items-center gap-3 px-4 py-3 border-b border-border hover:bg-bg-secondary transition-colors cursor-pointer ${completed ? 'opacity-100' : 'opacity-90'} ${isDropTarget ? 'border-accent/60 bg-accent/5' : ''}`}
    >

      <div className="flex items-center gap-2 pr-1">
        <GripVerticalIcon size={14} className="text-muted" aria-hidden />
      </div>

      {/* Checkbox */}
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          onToggle();
        }}
        className={`flex-shrink-0 w-5 h-5 rounded border-2 flex items-center justify-center transition-all duration-200 ${completed ? `${accent.bgClass} ${accent.borderClass} ${accent.shadowClass}` : 'border-border-hover hover:border-muted'}`}
        aria-label={`Mark ${habit.name} as ${completed ? 'incomplete' : 'complete'}`}>

        {completed &&
        <CheckIcon size={11} className={accent.textClass} strokeWidth={3} />
        }
      </button>

      {/* Icon + Name */}
      <button
        type="button"
        onClick={onDetail}
        className="flex items-center gap-2.5 flex-1 min-w-0 text-left">

        <span className="text-base leading-none">{habit.icon}</span>
        <div className="min-w-0">
          <div
            className={`text-sm font-medium ${completed ? 'text-muted line-through' : 'text-foreground'} truncate`}>

            {habit.name}
          </div>
          <div className="flex items-center gap-2 mt-0.5">
            {habit.tags.slice(0, 2).map((tag) =>
            <span
              key={tag}
              className="inline-flex items-center gap-1 text-[10px] font-mono text-foreground bg-bg-card border border-border rounded px-1.5 py-0.5">
                <span
                className="w-1.5 h-1.5 rounded-full"
                style={{ backgroundColor: accent.hex }} />
                {tag}
              </span>
            )}
          </div>
        </div>
      </button>

      {/* 30-day Mini Heatmap */}
      <div className="flex items-center justify-end mr-1" aria-hidden>
        <MiniHeatmap completions={habit.completions} color={habit.color} />
      </div>

      {/* Last 7 days mini bars */}
      <div className="flex items-end gap-[1px] h-4 sm:h-5" aria-hidden>
        {last7.map((done, i) =>
        <div
          key={i}
          className="w-[4px] rounded-sm transition-all"
          style={{
            height: done ? '100%' : '30%',
            backgroundColor: done ? accent.hex : 'var(--border)',
            opacity: i === 6 ? 1 : 0.5 + i * 0.07
          }} />

        )}
      </div>

      {/* Streak */}
      <div className="flex items-center gap-1 w-12 sm:w-16 justify-end">
        {streak > 0 &&
        <>
            <FlameIcon size={11} className="text-accent-secondary" />
            <span className="text-[11px] font-mono text-accent-secondary">
              {streak}
            </span>
          </>
        }
      </div>

      {/* Completion ring */}
      <CompletionRing
        percentage={completionRate}
        size={32}
        strokeWidth={2.5}
        color={habit.color}
        showText={false} />


      {/* Chevron */}
      <button
        type="button"
        onClick={onDetail}
        aria-label={`Open details for ${habit.name}`}
        className="text-border-hover group-hover:text-muted transition-colors">

        <ChevronRightIcon size={14} />
      </button>
    </div>);

}

function DropIndicator() {
  return (
    <div className="px-4 py-1">
      <div className="h-[3px] w-full rounded-full bg-gradient-to-r from-accent to-accent-secondary animate-pulse transition-all" />
    </div>
  );
}

export function Dashboard() {
  const navigate = useNavigate();
  const {
    habits,
    toggleCompletion,
    addHabit,
    updateHabit,
    getTodayCompletionRate,
    formatDate
  } = useHabits();
  const [draggedHabitId, setDraggedHabitId] = useState<string | null>(null);
  const [dragOverHabitId, setDragOverHabitId] = useState<string | null>(null);
  const [dropHint, setDropHint] = useState<{ habitId: string; position: 'above' | 'below' } | null>(null);
  const reminderTracker = useRef<Record<string, string>>({});
  const reminderLastCheckRef = useRef<number | null>(null);
  const [reminders, setReminders] = useState<Reminder[]>([]);
  const sendBrowserNotification = useCallback((habit: Habit) => {
    if (typeof window === 'undefined') {
      return;
    }
    if (!('Notification' in window)) {
      return;
    }
    if (Notification.permission !== 'granted') {
      return;
    }
    try {
      new Notification('Habbit reminder', {
        body: `Time for: ${habit.name}`,
        tag: `habit-reminder-${habit.id}`
      });
    } catch {
      // ignore failures from browsers that block without throwing
    }
  }, []);
  const applySortOrder = useCallback(
    async (orderedHabits: Habit[]) => {
      await Promise.all(
        orderedHabits.map((habit, index) => {
          const targetOrder = index;
          if (habit.sortOrder === targetOrder) {
            return Promise.resolve();
          }
          return updateHabit(habit.id, { sortOrder: targetOrder });
        })
      );
    },
    [updateHabit]
  );
  const handleDragStart = useCallback(
    (event: React.DragEvent<HTMLDivElement>, habitId: string) => {
      event.dataTransfer?.setData('text/plain', habitId);
      event.dataTransfer?.setDragImage(new Image(), 0, 0);
      setDraggedHabitId(habitId);
      setDropHint(null);
    },
    []
  );
  const handleDragOver = useCallback(
    (event: React.DragEvent<HTMLDivElement>, habitId: string) => {
      event.preventDefault();
      if (!draggedHabitId || draggedHabitId === habitId) {
        setDropHint(null);
        setDragOverHabitId(null);
        return;
      }
      const bounds = event.currentTarget.getBoundingClientRect();
      const midpoint = bounds.top + bounds.height / 2;
      const position = event.clientY < midpoint ? 'above' : 'below';
      setDropHint({ habitId, position });
      setDragOverHabitId(habitId);
    },
    [draggedHabitId]
  );
  const handleDrop = useCallback(
    async (event: React.DragEvent<HTMLDivElement>, habitId: string) => {
      event.preventDefault();
      if (!draggedHabitId || draggedHabitId === habitId) {
        setDragOverHabitId(null);
        setDraggedHabitId(null);
        return;
      }
      const original = [...habits];
      const sourceIndex = original.findIndex((habit) => habit.id === draggedHabitId);
      const targetIndex = original.findIndex((habit) => habit.id === habitId);
      if (sourceIndex === -1 || targetIndex === -1) {
        setDragOverHabitId(null);
        setDraggedHabitId(null);
        return;
      }
      const position =
        dropHint?.habitId === habitId
          ? dropHint.position
          : (() => {
              const bounds = event.currentTarget.getBoundingClientRect();
              const midpoint = bounds.top + bounds.height / 2;
              return event.clientY < midpoint ? 'above' : 'below';
            })();
      const ordered = [...original];
      const [moved] = ordered.splice(sourceIndex, 1);
      let insertIndex = targetIndex + (position === 'below' ? 1 : 0);
      if (sourceIndex < insertIndex) {
        insertIndex = Math.max(0, insertIndex - 1);
      }
      insertIndex = Math.max(0, Math.min(ordered.length, insertIndex));
      ordered.splice(insertIndex, 0, moved);
      await applySortOrder(ordered);
      setDragOverHabitId(null);
      setDraggedHabitId(null);
      setDropHint(null);
    },
    [applySortOrder, draggedHabitId, habits, dropHint]
  );
  const handleDragEnd = useCallback(() => {
    setDraggedHabitId(null);
    setDragOverHabitId(null);
    setDropHint(null);
  }, []);
  useEffect(() => {
    const checkReminders = () => {
      const nowTs = Date.now();
      const now = new Date(nowTs);
      const nowMinutes = now.getHours() * 60 + now.getMinutes();
      const nowDayKey = formatDate(now);
      const previousTs = reminderLastCheckRef.current ?? nowTs;
      reminderLastCheckRef.current = nowTs;
      const previous = new Date(previousTs);
      const previousMinutes = previous.getHours() * 60 + previous.getMinutes();
      const previousDayKey = formatDate(previous);

      habits.forEach((habit) => {
        if (!habit.reminderTime || habit.archived || habit.reminderEnabled === false) {return;}
        if (reminderTracker.current[habit.id] === nowDayKey) {return;}
        const reminderMinutes = parseReminderMinutes(habit.reminderTime);
        if (reminderMinutes === null) {return;}
        const crossedReminderTime =
          previousDayKey === nowDayKey
            ? reminderMinutes > previousMinutes && reminderMinutes <= nowMinutes
            : nowMinutes >= reminderMinutes;
        if (!crossedReminderTime) {return;}
        reminderTracker.current[habit.id] = nowDayKey;
        setReminders((prev) =>
          prev.some((item) => item.habitId === habit.id)
            ? prev
            : [
                ...prev,
                {
                  habitId: habit.id,
                  time: habit.reminderTime,
                message: `Reminder: ${habit.name} (${habit.reminderTime})`
              }
            ]
        );
        sendBrowserNotification(habit);
      });
    };
    checkReminders();
    if (typeof window === 'undefined') {
      return;
    }
    const interval = window.setInterval(checkReminders, 30_000);
    const onVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        checkReminders();
      }
    };
    document.addEventListener('visibilitychange', onVisibilityChange);
    return () => {
      window.clearInterval(interval);
      document.removeEventListener('visibilitychange', onVisibilityChange);
    };
  }, [formatDate, habits, sendBrowserNotification]);
  useEffect(() => {
    setReminders((prev) =>
      prev.filter((reminder) => habits.some((habit) => habit.id === reminder.habitId))
    );
  }, [habits]);
  const handleDismissReminder = useCallback((habitId: string) => {
    setReminders((prev) => prev.filter((reminder) => reminder.habitId !== habitId));
  }, []);
  const { push } = useUndo();
  const [addingTemplate, setAddingTemplate] = useState<string | null>(null);

  const handleTemplateSelect = useCallback(
    async (template: OnboardingTemplate) => {
      setAddingTemplate(template.name);
      try {
        const newId = await addHabit({
          name: template.name,
          description: template.description,
          icon: template.icon,
          color: template.color,
          tags: template.tags,
          frequency: template.frequency,
          customDays: template.customDays,
          targetStreak: template.targetStreak
        });
        navigate(`/habit/${newId}`);
      } finally {
        setAddingTemplate(null);
      }
    },
    [addHabit, navigate]
  );

  const [filter, setFilter] = useState<'all' | 'pending' | 'done'>('all');
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const today = formatDate(new Date());
  const todayRate = getTodayCompletionRate();
  const completedToday = habits.filter((h) => h.completions[today]).length;
  const totalActive = habits.length;
  const dateStr = formatAppDate(new Date(), {
    weekday: 'long',
    month: 'short',
    day: 'numeric'
  });
  const allTags = useMemo(() => {
    const tags = new Set<string>();
    habits.forEach((habit) => {
      habit.tags.forEach((tag) => tags.add(tag));
    });
    return Array.from(tags).sort();
  }, [habits]);

  const filtered = useMemo(() => {
    return habits.filter((h) => {
      if (filter === 'pending') {
        return !h.completions[today];
      }
      if (filter === 'done') {
        return !!h.completions[today];
      }
      if (selectedTags.length > 0 && !selectedTags.some((tag) => h.tags.includes(tag))) {
        return false;
      }
      return true;
    });
  }, [habits, filter, selectedTags, today]);

  const handleToggle = useCallback(
    async (habit: Habit) => {
      const wasDone = habit.completions[today];
      await toggleCompletion(habit.id, today);
      push({
        message: wasDone ? `Unchecked: ${habit.name}` : `Checked: ${habit.name}`,
        actionLabel: 'Undo',
        onUndo: async () => {
          await toggleCompletion(habit.id, today);
        }
      });
      handleDismissReminder(habit.id);
    },
    [push, today, toggleCompletion, handleDismissReminder]
  );

  const handleExport = useCallback(() => {
    if (typeof document === 'undefined') {
      return;
    }
    if (habits.length === 0) {
      return;
    }
    const escape = (value: string) => `"${value.replace(/"/g, '""')}"`;
    const rows = habits.map((habit) => {
      const completionDates = Object.entries(habit.completions)
        .filter(([, done]) => done)
        .map(([date]) => date);
      return [
        escape(habit.name),
        escape(habit.description),
        escape(habit.tags.join('|')),
        escape(JSON.stringify(completionDates))
      ].join(',');
    });
    const csv = ['name,description,tags,completions', ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `habits-export-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [habits]);

  const toggleTag = useCallback((tag: string) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((item) => item !== tag) : [...prev, tag]
    );
  }, []);

  if (habits.length === 0) {
    return (
      <div className="min-h-screen bg-bg-primary pt-14">
        <Onboarding
          onCreateCustom={() => navigate('/habit/new')}
          onTemplateSelect={handleTemplateSelect}
          activeTemplate={addingTemplate}
        />
      </div>
    );
  }

  // Overall streak (days where all habits completed)
  let overallStreak = 0;
  const d = new Date();
  d.setDate(d.getDate() - 1);
  for (let i = 0; i < 30; i++) {
    const key = d.toISOString().split('T')[0];
    const allDone = habits.every((h) => h.completions[key]);
    if (allDone) {
      overallStreak++;
      d.setDate(d.getDate() - 1);
    } else {
      break;
    }
  }

  return (
    <div className="min-h-screen bg-bg-primary pt-14">
      {/* Header */}
      <div className="border-b border-border bg-bg-primary px-4 py-4">
        <div className="max-w-2xl mx-auto">
          <div className="flex items-start justify-between mb-4">
            <div>
              <p className="text-[11px] font-mono text-muted uppercase tracking-widest mb-1">
                {dateStr}
              </p>
              <h1 className="text-xl font-semibold text-foreground">Today</h1>
            </div>
            <div className="text-right">
              <div
                className="text-3xl font-mono font-bold text-accent"
                style={{
                  textShadow: '0 0 20px var(--glow)'
                }}
              >
                {todayRate}%
              </div>
              <div className="text-[10px] font-mono text-muted">
                {completedToday}/{totalActive} done
              </div>
            </div>
          </div>
          <div className="h-1 bg-border rounded-full overflow-hidden mb-4">
            <div
              className="h-full rounded-full transition-all duration-700"
              style={{
                width: `${todayRate}%`,
                background: 'linear-gradient(90deg, var(--accent), var(--accent-secondary))',
                boxShadow: '0 0 8px var(--glow)'
              }}
            />
          </div>
          <div className="flex items-center justify-between gap-3">
            <div className="text-[10px] font-mono uppercase tracking-[0.4em] text-muted">
              Filters
            </div>
            <button
              type="button"
              onClick={handleExport}
              className="text-[10px] font-mono uppercase tracking-[0.3em] border border-border px-3 py-1 rounded-full transition hover:border-accent hover:text-accent"
            >
              Export CSV
            </button>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-3 gap-2 mt-4">
            <div className="bg-bg-secondary border border-border rounded-lg px-3 py-2">
              <div className="flex items-center gap-1.5 mb-1">
                <ZapIcon size={10} className="text-accent" />
                <span className="text-[10px] font-mono text-muted uppercase tracking-wider">
                  Active
                </span>
              </div>
              <span className="text-lg font-mono font-bold text-foreground">
                {totalActive}
              </span>
            </div>
            <div className="bg-bg-secondary border border-border rounded-lg px-3 py-2">
              <div className="flex items-center gap-1.5 mb-1">
                <FlameIcon size={10} className="text-accent-secondary" />
                <span className="text-[10px] font-mono text-muted uppercase tracking-wider">
                  Streak
                </span>
              </div>
              <span className="text-lg font-mono font-bold text-accent-secondary">
                {overallStreak}d
              </span>
            </div>
            <div className="bg-bg-secondary border border-border rounded-lg px-3 py-2">
              <div className="flex items-center gap-1.5 mb-1">
                <TrendingUpIcon size={10} className="text-accent-secondary" />
                <span className="text-[10px] font-mono text-muted uppercase tracking-wider">
                  Done
                </span>
              </div>
              <span className="text-lg font-mono font-bold text-accent-secondary">
                {completedToday}
              </span>
            </div>
          </div>
        </div>
      </div>

      {reminders.length > 0 && (
        <div className="max-w-2xl mx-auto px-4 py-3 space-y-2">
          {reminders.map((reminder) => {
            const habit = habits.find((item) => item.id === reminder.habitId);
            if (!habit) {return null;}
            return (
              <div
                key={reminder.habitId}
                className="flex flex-col gap-2 rounded-2xl border border-accent/20 bg-accent/5 px-4 py-3"
              >
                <div className="flex items-center gap-2">
                  <BellRingIcon size={16} className="text-accent-secondary" />
                  <div className="text-sm font-semibold text-foreground">
                    {reminder.message}
                  </div>
                  <span className="text-[10px] font-mono text-muted ml-auto">
                    {reminder.time}
                  </span>
                </div>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => handleToggle(habit)}
                    className="flex-1 rounded-full border border-accent px-3 py-1.5 text-[10px] font-mono uppercase tracking-[0.3em] text-accent hover:bg-accent/10 transition-colors"
                  >
                    Mark done
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDismissReminder(habit.id)}
                    className="flex-1 rounded-full border border-border px-3 py-1.5 text-[10px] font-mono uppercase tracking-[0.3em] text-muted hover:text-foreground hover:border-border-hover transition-colors"
                  >
                    Dismiss
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Filter tabs */}
      <div className="border-b border-border px-4">
        <div className="max-w-2xl mx-auto">
          <div className="flex gap-0">
          {(['all', 'pending', 'done'] as const).map((f) =>
          <button
            key={f}
            type="button"
            onClick={() => setFilter(f)}
            className={`px-4 py-2.5 text-xs font-mono uppercase tracking-wider border-b-2 transition-colors ${filter === f ? 'border-accent text-accent' : 'border-transparent text-muted hover:text-foreground'}`}>

              {f}
              {f === 'pending' &&
            <span className="ml-1.5 text-[9px] bg-border px-1 py-0.5 rounded font-mono">
                  {habits.filter((h) => !h.completions[today]).length}
                </span>
            }
            </button>
          )}
          </div>
          <div className="py-2.5 flex items-center gap-1.5 overflow-x-auto">
            {allTags.length > 0 ? (
              <>
                {allTags.map((tag) =>
                  <button
                    key={tag}
                    type="button"
                    onClick={() => toggleTag(tag)}
                    className={`text-[10px] font-mono px-2 py-1 rounded border whitespace-nowrap transition-colors ${selectedTags.includes(tag) ? 'bg-accent/10 border-accent/30 text-accent' : 'bg-bg-secondary border-border text-muted hover:text-foreground hover:border-border-hover'}`}>
                    #{tag}
                  </button>
                )}
                {selectedTags.length > 0 && (
                  <button
                    type="button"
                    onClick={() => setSelectedTags([])}
                    className="text-[10px] font-mono px-2 py-1 rounded border whitespace-nowrap bg-bg-secondary border-accent/30 text-accent hover:bg-accent/10 transition-colors"
                  >
                    Clear tags
                  </button>
                )}
              </>
            ) : (
              <span className="text-[10px] font-mono text-muted">No tags yet</span>
            )}
          </div>
        </div>
      </div>

      {/* Habit list */}
      <div className="max-w-2xl mx-auto py-6 space-y-1" role="list" aria-label="Habit list">
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-muted">
            <div className="text-4xl mb-3">✓</div>
            <p className="font-mono text-sm">All habits are currently paused</p>
          </div>
        ) : (
          filtered.map((habit) => (
            <React.Fragment key={habit.id}>
              {dropHint?.habitId === habit.id && dropHint.position === 'above' && (
                <DropIndicator />
              )}
              <HabitRow
                habit={habit}
                onToggle={() => handleToggle(habit)}
                onDetail={() => navigate(`/habit/${habit.id}`)}
                onDragStart={(event) => handleDragStart(event, habit.id)}
                onDragOver={(event) => handleDragOver(event, habit.id)}
                onDrop={(event) => handleDrop(event, habit.id)}
                onDragEnd={handleDragEnd}
                isDropTarget={dragOverHabitId === habit.id}
              />
              {dropHint?.habitId === habit.id && dropHint.position === 'below' && (
                <DropIndicator />
              )}
            </React.Fragment>
          ))
        )}
      </div>
    </div>);

}
