// packages/web/src/components/HeatmapGrid.tsx
import React, { useMemo, useState } from 'react';
import { DEFAULT_HABIT_COLOR, HABIT_COLOR_THEMES } from '@/lib/theme/habit-colors';
import type { HabitColor } from '@/types/habit';

interface HeatmapGridProps {
  completions: Record<string, number>;
  dailyTarget?: number;
  color?: HabitColor;
  weeks?: number;
}

type HeatmapCell = {
  date: string;
  completed: boolean;
  isToday: boolean;
};

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}

function getIntensity(completed: boolean | undefined): number {
  return completed ? 4 : 0;
}

const DAY_LABEL_WIDTH = 16;

function buildHeatmapCells(
  completions: Record<string, number>,
  dailyTarget: number,
  weeks: number
): HeatmapCell[][] {
  const today = new Date();
  const cells: HeatmapCell[][] = [];
  const startDate = new Date(today);
  const weekStartOffset = (startDate.getDay() + 6) % 7;
  startDate.setDate(startDate.getDate() - weekStartOffset - (weeks - 1) * 7);

  for (let w = 0; w < weeks; w++) {
    const week: HeatmapCell[] = [];
    for (let d = 0; d < 7; d++) {
      const date = new Date(startDate);
      date.setDate(startDate.getDate() + w * 7 + d);
      const dateStr = formatDate(date);
      week.push({
        date: dateStr,
        completed: (completions[dateStr] ?? 0) >= dailyTarget,
        isToday: dateStr === formatDate(today)
      });
    }
    cells.push(week);
  }
  return cells;
}

function buildMonthLabels(cells: HeatmapCell[][]): { label: string; col: number }[] {
  const labels: { label: string; col: number }[] = [];
  let lastMonth = -1;

  cells.forEach((week, index) => {
    const month = new Date(week[0].date).getMonth();
    if (month !== lastMonth) {
      labels.push({
        label: new Date(week[0].date).toLocaleString('default', { month: 'short' }),
        col: index
      });
      lastMonth = month;
    }
  });

  return labels;
}

function DayLabels() {
  const dayLabels = ['M', 'W', 'F'];
  return (
    <div className="grid shrink-0 gap-1 sm:gap-1.5 mr-1.5" style={{ width: DAY_LABEL_WIDTH, gridTemplateRows: 'repeat(7, minmax(0, 1fr))' }}>
      {Array.from({ length: 7 }, (_, index) => (
        <div
          key={index}
          className="text-[9px] font-mono text-muted flex items-center"
        >
          {index === 0 ? dayLabels[0] : index === 2 ? dayLabels[1] : index === 4 ? dayLabels[2] : ''}
        </div>
      ))}
    </div>
  );
}

function MonthLabels({ labels, weeks }: { labels: { label: string; col: number }[]; weeks: number }) {
  return (
    <div className="relative mb-1 ml-[18px] h-4">
      {labels.map((label) => (
        <div
          key={`${label.label}-${label.col}`}
          className="absolute text-[9px] font-mono text-muted whitespace-nowrap -translate-y-1"
          style={{ left: `${(label.col / weeks) * 100}%` }}
        >
          {label.label}
        </div>
      ))}
    </div>
  );
}

function HeatmapCells({
  cells,
  levels,
  glow,
  today,
  onHover,
  onLeave
}: {
  cells: HeatmapCell[][];
  levels: string[];
  glow: string;
  today: Date;
  onHover: (cell: HeatmapCell, event: React.MouseEvent<HTMLDivElement>) => void;
  onLeave: () => void;
}) {
  return (
    <div className="grid flex-1 gap-1 sm:gap-1.5" style={{ gridTemplateColumns: `repeat(${cells.length}, minmax(0, 1fr))` }}>
      {cells.map((week, wi) => (
        <div key={wi} className="grid gap-1 sm:gap-1.5" style={{ gridTemplateRows: 'repeat(7, minmax(0, 1fr))' }}>
          {week.map((cell, di) => {
            const intensity = getIntensity(cell.completed);
            const bg = levels[intensity];
            const isFuture = new Date(cell.date) > today;
            return (
              <div
                key={di}
                className="aspect-square w-full rounded-[2px] cursor-pointer transition-transform hover:scale-110"
                style={{
                  backgroundColor: isFuture ? 'var(--bg-secondary)' : intensity === 0 ? 'var(--border)' : bg,
                  opacity: isFuture ? 0.3 : 1,
                  boxShadow:
                    cell.completed && !isFuture ? `0 0 4px ${glow}` : 'none',
                  outline: cell.isToday ? `1px solid ${levels[4]}` : 'none',
                  outlineOffset: '1px'
                }}
                onMouseEnter={(event) => onHover(cell, event)}
                onMouseLeave={onLeave}
              />
            );
          })}
        </div>
      ))}
    </div>
  );
}

function HeatmapTooltip({ tooltip }: { tooltip: { x: number; y: number; completed: boolean; date: string } | null }) {
  if (!tooltip) {
    return null;
  }
  return (
    <div
      className="fixed z-50 pointer-events-none px-2 py-1 rounded bg-bg-card border border-border text-[10px] font-mono text-foreground shadow-lg"
      style={{ left: tooltip.x + 16, top: tooltip.y - 28 }}>
      <span className={tooltip.completed ? 'text-accent-secondary' : 'text-muted'}>
        {tooltip.completed ? '✓' : '○'}
      </span>{' '}
      {tooltip.date}
    </div>
  );
}

export function HeatmapGrid({
  completions,
  dailyTarget = 1,
  color = DEFAULT_HABIT_COLOR,
  weeks = 26
}: HeatmapGridProps) {
  const [tooltip, setTooltip] = useState<{
    date: string;
    completed: boolean;
    x: number;
    y: number;
  } | null>(null);
  const today = useMemo(() => new Date(), []);
  const cells = useMemo(
    () => buildHeatmapCells(completions, dailyTarget, weeks),
    [completions, dailyTarget, weeks]
  );
  const monthLabels = useMemo(() => buildMonthLabels(cells), [cells]);
  const { heatmapLevels: levels, glow } = HABIT_COLOR_THEMES[color];

  const handleHover = (cell: HeatmapCell, event: React.MouseEvent<HTMLDivElement>) => {
    const rect = event.currentTarget.getBoundingClientRect();
    setTooltip({
      date: cell.date,
      completed: cell.completed,
      x: rect.left,
      y: rect.top
    });
  };

  return (
    <div className="relative select-none">
      <MonthLabels labels={monthLabels} weeks={weeks} />
      <div className="flex w-full gap-0">
        <DayLabels />
        <HeatmapCells
          cells={cells}
          levels={levels}
          glow={glow}
          today={today}
          onHover={handleHover}
          onLeave={() => setTooltip(null)}
        />
      </div>
      <HeatmapTooltip tooltip={tooltip} />
    </div>
  );
}

// apps/web-svelte/src/lib/components/HeatmapGrid.svelte
<script lang="ts">
  import { formatAppDate } from '$lib/i18n';
  import { normalizeToCompletionKey } from '$lib/completionKey';

  type HeatmapDay = {
    date: string;
    intensity: number;
    isFrozen: boolean;
    inWindow: boolean;
  };

  type HeatmapWeek = {
    label: string;
    days: HeatmapDay[];
  };

  let {
    weeks,
    accentHex = 'var(--accent)',
    accentGlow = 'var(--glow)'
  }: {
    weeks: HeatmapWeek[];
    accentHex?: string;
    accentGlow?: string;
  } = $props();

  const FILL_OPACITIES = [0, 0.22, 0.46, 0.72, 1.0];
  const totalWeeks = $derived(weeks.length);
  const DAY_LABELS = ['M', '', 'W', '', 'F', '', ''];

  let tooltip = $state<{ x: number; y: number; text: string } | null>(null);

  function cellStyle(day: HeatmapDay): string {
    if (!day.inWindow) return 'background-color: transparent; opacity: 0';
    if (day.isFrozen) return 'background-color: var(--accent); opacity: 0.15';
    if (day.intensity === 0) return 'background-color: var(--border); opacity: 0.5';
    const opacity = FILL_OPACITIES[day.intensity] ?? 1;
    return `background-color: ${accentHex}; opacity: ${opacity}; box-shadow: 0 0 4px ${accentGlow}`;
  }

  function today() {
    const d = new Date();
    return d.toISOString().split('T')[0];
  }

  const todayStr = today();

  function cellOutline(day: HeatmapDay): string {
    return day.date === todayStr ? `1px solid ${accentHex}` : 'none';
  }

  function handleHover(day: HeatmapDay, event: MouseEvent) {
    if (!day.inWindow) return;
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const parsed = new Date(normalizeToCompletionKey(day.date));
    const text = formatAppDate(parsed, { weekday: 'short', month: 'short', day: 'numeric' });
    tooltip = { x: rect.left + 8, y: rect.top - 28, text };
  }
</script>

<div class="relative select-none">
  <div class="flex w-full gap-0">
    <div
      class="grid shrink-0 gap-1 sm:gap-1.5 mr-1.5"
      style="width: 16px; grid-template-rows: repeat(7, minmax(0, 1fr))"
    >
      {#each DAY_LABELS as label}
        <div class="text-[9px] font-mono text-muted flex items-center">{label}</div>
      {/each}
    </div>

    <div
      class="grid flex-1 gap-1 sm:gap-1.5"
      style="grid-template-columns: repeat({totalWeeks}, minmax(0, 1fr))"
    >
      {#each weeks as week}
        <div class="grid gap-1 sm:gap-1.5" style="grid-template-rows: repeat(7, minmax(0, 1fr))">
          {#each week.days as day}
            <div
              class="aspect-square w-full rounded-[2px] transition-transform hover:scale-110"
              style="{cellStyle(day)}; cursor: {day.inWindow ? 'pointer' : 'default'}; outline: {cellOutline(day)}; outline-offset: 1px;"
              onmouseenter={(e) => handleHover(day, e)}
              onmouseleave={() => (tooltip = null)}
            ></div>
          {/each}
        </div>
      {/each}
    </div>
  </div>

  {#if weeks.length > 0}
    <div class="relative mt-1 h-4 ml-[18px] overflow-hidden">
      {#each weeks as w, idx}
        {#if idx === 0 || weeks[idx - 1]?.days[0]?.date.slice(5, 7) !== w.days[0]?.date.slice(5, 7)}
          {@const parsed = new Date(normalizeToCompletionKey(w.days[0].date))}
          <span
            class="absolute text-[9px] font-mono text-muted"
            style="left: {(idx / totalWeeks) * 100}%"
          >
            {parsed.toLocaleString('default', { month: 'short' })}
          </span>
        {/if}
      {/each}
    </div>
  {/if}

  {#if tooltip}
    <div
      class="fixed z-50 pointer-events-none px-2 py-1 rounded bg-bg-card border border-border text-[10px] font-mono text-foreground shadow-lg"
      style="left: {tooltip.x}px; top: {tooltip.y}px"
    >
      {tooltip.text}
    </div>
  {/if}
</div>
