// src/components/UndoToast.tsx
import React from 'react';

interface Props {
  message: string;
  actionLabel: string;
  onAction: () => void;
  onClose: () => void;
}

export function UndoToast({ message, actionLabel, onAction, onClose }: Props) {
  return (
    <div className="fixed left-1/2 bottom-6 z-50 w-full max-w-lg -translate-x-1/2 bg-bg-secondary/90 backdrop-blur-xl border border-border rounded-2xl px-4 py-3 shadow-xl flex items-center justify-between gap-4 text-sm text-foreground">
      <div>
        <p className="text-[11px] font-mono uppercase tracking-[0.3em] text-muted">undo</p>
        <p className="mt-1 text-base font-semibold">{message}</p>
      </div>
      <div className="flex items-center gap-2">
        <button
          type="button"
          className="rounded-full border border-accent px-3 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-accent transition hover:border-accent-secondary/60"
          onClick={onAction}
        >
          {actionLabel}
        </button>
        <button
          type="button"
          className="text-xs font-mono uppercase tracking-[0.3em] text-muted"
          onClick={onClose}
        >
          ×
        </button>
      </div>
    </div>
  );
}

// apps/web-svelte/src/lib/components/UndoToast.svelte
<script lang="ts">
  let {
    message,
    onUndo,
    onDismiss
  }: {
    message: string;
    onUndo: () => void;
    onDismiss: () => void;
  } = $props();
</script>

<div
  class="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 flex items-center gap-3 rounded-xl border border-border bg-bg-card/95 backdrop-blur-lg px-4 py-3 shadow-2xl min-w-[240px] max-w-[90vw] animate-slide-up"
>
  <span class="text-sm text-foreground flex-1 min-w-0 truncate">{message}</span>
  <button
    type="button"
    onclick={onUndo}
    class="text-xs font-bold text-accent hover:underline whitespace-nowrap"
  >
    Undo
  </button>
  <button
    type="button"
    onclick={onDismiss}
    class="text-muted hover:text-foreground text-sm leading-none ml-1"
    aria-label="Dismiss"
  >
    ×
  </button>
</div>
